### ISSUE TITLE
Write tests for menus

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#11]
On our meeting last Thursday @heatherleaf mentioned that we should add some tests for menus. I've written the test-runner. If you could help me come up with some nice test-cases that would be great:

https://github.com/MUSTE-Project/MULLE/blob/d0a077ff2ca781772d093bc5144e586321b1ac16/muste/test/Test/Menu.hs#L43-L46

**Comment by heatherleaf** [comment]
It's difficult to come up with trees, and they can change whenever we update the grammar. It's easier to compare linearisations, but then we to add another string to the `mkTests` tuples -- the language to parse.

Here are some first suggestions of test cases:

```
tests = testGroup "Menu" $ mkTests
  [ ("REPL: fienden", "ExemplumSwe", "fienden besegrar Afrika", [0], "en fiende besegrar Afrika"),
    ("REPL: fienden", "ExemplumSwe", "fienden besegrar Afrika", [0], "Augustus besegrar Afrika"),
    ("REPL: besegrar", "ExemplumSwe", "fienden besegrar Afrika", [1], "fienden är Afrika"),
    ("REPL: Afrika", "ExemplumSwe", "fienden är Afrika", [2], "fienden är stor"),
    ("REPL: Afrika", "ExemplumSwe", "fienden är Afrika", [2], "fienden är en vän"),
    ("DEL: det besegrade", "ExemplumSwe", "det besegrade riket är stort", [0,1], "fienden besegrar Afrika"),
    ("INS: det besegrade", "ExemplumSwe", "fienden besegrar Afrika", [], "det besegrade riket är stort"), -- NOTE: the "selection" should really be an insertion BEFORE "fienden" -- how do we represent that?
  ] 
```

Now, `mkTests` need to be updated to parse strings not trees. Now you're using `(parseTree src)`, which uses `read` and `Muste.Grammar.Internal.fromGfTree`. Instead you should use the following from PGF:

    parse :: PGF -> Language -> Type -> String -> [Tree]

Here, `PGF` is the grammar, `Language` is "ExemplumSwe", `Type` is the startcat of the grammar (`Utt` in the `novo_modo` grammars -- for now we can hard-code that, but it should be possible to extract from the PGF). The `String` is the string to parse and the returned `Tree`s are GF trees which have to be converted to `TTree`.

You also have to accommodate that parsing returns a list of trees. But the idea is that *at least one* of the source trees can be converted to one of the target trees.

**Comment by fredefox** [comment]
> You also have to accommodate that parsing returns a list of trees. But the idea is that at least one of the source trees can be converted to one of the target trees.

Ah, good. This was one of the tricky bits. I think we should just remove `Grammar.Internal.parseTTree` in favor of `Grammar.Internal.parseSentence` as I think this does what you specified.

**Comment by fredefox** [comment]
Correction. `parseTTree` is still useful of course.

**Comment by heatherleaf** [comment]
The two first trees in `mkLin` are the source and target trees in the exercise. I.e., the Latin and the Swedish sentence in the webapp. The third tree is the tree you want to linearise, which can be either the source or the target tree. This is done in `DBInit.exercises`, line 70 (`DBInit.hs`):

    go srcC trgC idfE (src, trg) = (srcC src trg src, trgC src trg trg, idfE)

If you want to use `mkLin` in the tests, where you only have one tree, you can use `mkLin cxt t t t`, i.e. use the same tree in all three positions. It doesn't matter for the tests in in `Menu.hs` (at least not now).

**Comment by heatherleaf** [comment]
Is it possible to add both positive and negative tests? E.g.:

```
tests = testGroup "Menu" $ mkTests
  [ (True, "REPL: fienden", "ExemplumSwe", "fienden besegrar Afrika", [0], "Augustus besegrar Afrika"),
    (False, "REPL: fienden", "ExemplumSwe", "fienden besegrar Afrika", [0,1], "Augustus besegrar Afrika"),
```

This would then mean that ("fienden" --> "Augustus"), but not ("fienden besegrar" --> "Augustus besegrar"). I.e., that "Augustus besegrar Afrika" should be in the [0] menu, not in the [0,1] menu.

**Comment by heatherleaf** [comment]
This would be useful in the `Prune` tests, because they are mainly negative. The `Prune` tests could be quite similar to the `Menu` tests. Here are some suggestions:

```
Menu.tests = testGroup "Menu" $ mkTests
  [ (True, "Augustus->en fiende", "ExemplumSwe", "Augustus besegrar Afrika", [0], "en fiende besegrar Afrika"),
    (True, "->stor", "ExemplumSwe", "en fiende besegrar Afrika", [], "en stor fiende besegrar Afrika") ]

Prune.tests = testGroup "Prune" $ mkTests
  [ (False, "Augustus->en stor fiende", "ExemplumSwe", "Augustus besegrar Afrika", "en stor fiende besegrar Afrika") ]
```

Here's another suggestion how the Prune tests could be written:

```
Prune.tests = testGroup "Prune" $ mkTests
  [ ("Augustus->en fiende->en stor fiende", "ExemplumSwe", "Augustus besegrar Afrika", "en fiende besgrar Afrika", "en stor fiende besegrar Afrika") ]
```

This is short for 3 tests really: (1) assert that "Augustus -> en fiende", (2) assert that "fiende" -> "stor fiende", and (3) assert that ***not*** "Augustus -> en stor fiende"

**Comment by fredefox** [comment]
We now have the test-runner in place

https://github.com/MUSTE-Project/MULLE/blob/4f08d8203e0a68aad27f36a1a6ea5e8844caee27/muste/test/Test/Menu.hs#L62-L72

And hopefully somewhat helpful failure messages (in contrast with some of the other test-cases -- will fix):

          REPL: Afrika:                               FAIL
            Exception: user error (Expected to find one of:
             [ fienden är en vän ]
            Somewhere in:
            [TRUNCATED]: [ fienden är Augustus
            , fienden är Gallien
            , fienden är en far
            , fienden är en fiende
            , fienden är en flicka
            , fienden är en german
            , fienden är en gudom
            , fienden är en hustru ])

**Comment by fredefox** [comment]
We now also have support for negative tests:

https://github.com/MUSTE-Project/MULLE/blob/6445fa2bf15704033687f118c81c720b0d760d36/muste/test/Test/Menu.hs#L62-L76

Multiple test cases are still failing. @heatherleaf

**Comment by fredefox** [comment]
I've added a comment in the test-suite about the test-cases that are failing.

**Comment by heatherleaf** [comment]
Seems like there's some problem with the test runner:

         REPL: fienden 1:                            FAIL
            Exception: user error (Expected to find one of:
            [ Augustus besegrar Afrika ]
            Somewhere in:
            [RESULT TRUNCATED]:
            [ Afrika besegrar Afrika
            , Augustus besegrar Afrika
            , Gallien besegrar Afrika

          REPL: besegrar:                             FAIL
            Exception: user error (Expected to find one of:
            [ fienden är Afrika ]
            Somewhere in:
            [ fienden blir Afrika
            , fienden har Afrika
            , fienden håller Afrika
            , fienden säger Afrika
            , fienden är Afrika ])

          REPL: Afrika 1:                             FAIL
            Exception: user error (Expected to find one of:
            [ fienden är en vän ]
            Somewhere in:
            [RESULT TRUNCATED]:

As you can see, the expected value is already in the list. (Except the last example, but since the list is truncated I guess it's there somewhere). I can't understand `Test.Menu.mkTest'`, so I don't know where the error is. 

-----------

The following failures are strange:

          DEL: det besegrade:                         FAIL
            Exception: user error (Selection not found in menu for: "det besegrade riket är stort")

          REPL: fienden:                              FAIL
            Exception: user error (Selection not found in menu for: "fienden besegrar Afrika")

Those two are the only ones with a multiple-word selection (`[0,1]`), and apparently `getSuggestions` cannot lookup that selection in the string. 

-------------

Finally, this success is also strange:

          INS: det besegrade:                         OK (7.18s)

Because the selection is just an empty list (`[]`) -- which menu is that associated with?

**Comment by heatherleaf** [comment]
I updated the test cases in `Test.Menu.menuLin`, in commit e95ed0de968afed63a6bb19065be72ad0836097b

Most test cases still fail though, but there is probably some bug(s) in `mkTest'` since they look like they should succeed (see comment above).

**Comment by fredefox** [comment]
It's that *and* I accidentally put a negation in the wrong place. It's a bit tricky with triple-negatives.

**Comment by fredefox** [comment]
You can change the limit of suggestions shown at:

https://github.com/MUSTE-Project/MULLE/blob/e04101a5d925a2b1ae96916263f4aba18f39a919/muste/test/Test/Menu.hs#L99

E.g. set it to `maxBound`. If you don't think this feature is helpful we can remove it. I just put it in so I can see an overview of the tests that fail in stead of potentially having my terminal flooded with information from one test-case.

**Comment by fredefox** [comment]
>  can't understand `Test.Menu.mkTest'`

I've tried to address this in b79ac62035eb52265b2ba1bbaaddcf02cb33415b (note name-change of `mkTest'`):

https://github.com/MUSTE-Project/MULLE/blob/b79ac62035eb52265b2ba1bbaaddcf02cb33415b/muste/test/Test/Menu.hs#L62-L129

**Comment by fredefox** [comment]
I've now also updated the test-runner for pruning. It still just looks at `TTree`s and not `Linearization`s, but I think this makes sense. As you point out, the test would be very similar otherwise.

It makes sense that the module that tests `Muste.Prune` doesn't know about `Linearization`s since the module it tests doesn't know about it either.

Do you think it would be possible to cover what you feel is lacking in another place?

Quoting the relevant change:

https://github.com/MUSTE-Project/MULLE/blob/851f9efad99c9fe9f61fafaeab7ffd0281750c3e/muste/test/Test/Prune.hs#L20-L48

**Comment by heatherleaf** [comment]
I've commited some updates to the repo. One of them was to add the Exemplum grammar to the UI.

Then I noticed that the first Menu test ("fienden->en fiende") works in the browser: The example sentence in the browser is "fienden besegrar Afrika", and if I click "fienden" then "en fiende" is one of the menu items.

There are more items in the browser version that are not printed when I run "stack test". So, some bug in the testing still remains.

**Comment by heatherleaf** [comment]
One another side, I noticed that the failure of test 4 ("Afrika->stor") is correct (i.e., the test fails and it is because the menu is wrong).

In the browser, "stor" is not in the menu for "Afrika". But "är stor" is in the menu for "är Afrika" -- which means that the menu structure is not entirely correct yet.
