### ISSUE TITLE
Simple command line interface

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#14]
I want to be able to run a simple clicking simulation from the command line.

```
$ muste-cmd "ExemplumSwe" "fienden besegrar Afrika" 0
<fienden> besegrar Afrika
-------------------------------
<en fiende> besegrar Afrika
<Gallien> besegrar Afrika
<germanen> besegrar Afrika
etc
-------------------------------

$ muste-cmd "ExemplumSwe" "fienden besegrar Afrika" ins-0
<> fienden besegrar Afrika
-------------------------------
<den stora> fienden besegrar Afrika
<den glada> fienden besegrar Afrika
etc
-------------------------------

$ muste-cmd "ExemplumSwe" "den stora fienden besegrar Afrika" 0
<den> stora fienden besegrar Afrika
-------------------------------
<en> stor fiende besegrar Afrika
<alla> stora fiender besegrar Afrika
stora fiender besegrar Afrika
etc
-------------------------------

$ muste-cmd "ExemplumSwe" "den stora fienden besegrar Afrika" 01
<den stora> fienden besegrar Afrika
-------------------------------
fienden besegrar Afrika
-------------------------------

$ muste-cmd "ExemplumSwe" "fienden besegrar Afrika" 12
fienden <besegrar Afrika>
-------------------------------
fienden <är stor>
etc
-------------------------------
```

One problem is how to represent insertions. My suggestion above is ugly ("ins-0" instead of "0"), but I have no better idea. 

Or, here is one idea, but this will be difficult to interpret into a `Selection`. (The selection is implicitly described using "<>" in the sentence):

```
$ muste-cmd "ExemplumSwe" "<fienden> besegrar Afrika" 
<fienden> besegrar Afrika
-------------------------------
<en fiende> besegrar Afrika
<Gallien> besegrar Afrika
<germanen> besegrar Afrika
etc
-------------------------------
```

**Comment by heatherleaf** [comment]
Perhaps also a version which prints all menus:

```
$ muste-cmd "ExemplumSwe" "fienden besegrar Afrika" 
+-- 0 ---------------------------
| <fienden> besegrar Afrika
+--------------------------------
| <en fiende> besegrar Afrika
| <Gallien> besegrar Afrika
| ...
+--------------------------------

+-- insert-0 --------------------
| <> fienden besegrar Afrika
+--------------------------------
| <den stora> fienden besegrar Afrika
| <den glada> fienden besegrar Afrika
| ...
+--------------------------------

+-- 0 ---------------------------
| <den> stora fienden besegrar Afrika
+--------------------------------
| <en> stor fiende besegrar Afrika
| <alla> stora fiender besegrar Afrika
| stora fiender besegrar Afrika
| ...
+--------------------------------

+-- 01 --------------------------
| <den stora> fienden besegrar Afrika
+--------------------------------
| fienden besegrar Afrika
| ...
+--------------------------------

+-- 12 --------------------------
| fienden <besegrar Afrika>
+--------------------------------
| fienden <är stor>
| ...
+--------------------------------
```

Notes:
1. It doesn't have to look exactly like this of course.
2. I don't want to truncate the menus, so no `...` in the output.

**Comment by fredefox** [comment]
A thing /like/ this existed and was removed in

```
commit 0f97799bb921706f7ae69f8c492263fbc0199cec
Author: Frederik Hanghøj Iversen <fhi.1990@gmail.com>
Date:   Thu Jul 12 08:36:45 2018 +0200

    [WIP] General refactoring
    
    Left over changes from yesterday

...
D       muste-lib/Main.hs
...
```

(Great commit message Freddy -.-)

I'll put it back in

**Comment by fredefox** [comment]
I've had a look at it. I think with all the changes it may be easier for me to just quickly re-implement it. Any thoughts?

**Comment by fredefox** [comment]
I'm thinking I wanna make a GHCi-like interface for this using [`repline`](http://hackage.haskell.org/package/repline-0.1.7.0/docs/System-Console-Repline.html).

**Comment by heatherleaf** [comment]
Well, I guess you should use `Menu.getMenu`, but I don't know about how to make CLIs.

Don't overdo it: it's not necessary with a GHCi-like interface.

**Comment by fredefox** [comment]
I wasn't planning on overdoing it. I was planning on trying to meet the requirements in as easily as possible.

**Comment by fredefox** [comment]
You can have a look at this interface I made for finding [`rhyme`](https://github.com/fredefox/rhyme/blob/master/Rhyme.hs)s. It's 100 LOC. The difference between that interface and this is that here we need to have support for various commands - and that's why I was thinking of using `repline` because Stephen Diehl has implemented that functionality so I don't have to.

It's up to you of course. I can also try to get the old version running.

**Comment by heatherleaf** [comment]
If it's more boring to get the old version to work, and it won't save you lot of time, then go for your suggestion!

**Comment by fredefox** [comment]
Boom! Simple CLI. This version does not do highlighting. Run with:

    stack install
    muste-cli

**Comment by fredefox** [comment]
This version doesn't support "highlighting" of the selected words - but neither did the old one + replacements in the old one used deprecated logic. This version just used `Menu.getMenuFromStringRep` as previously discussed.

**Comment by fredefox** [comment]
For reference this is the old version:

https://github.com/MUSTE-Project/MULLE/blob/f3d0baa2e4e33aaf1f8f81a7d8157fb94aa27221/muste-lib/Main.hs#L1-L206

Compared to the new:

https://github.com/MUSTE-Project/MULLE/blob/1aa492130f8cf157902dcc1427035639d986b799/muste/app/Main.hs#L1-L156
