### ISSUE TITLE
The linearization to/from the GUI should not contain paths

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#15]
`Menu.getMenu` has the following type:

    getMenu :: Context -> Linearization -> Menu

But a `Linearization` consists of `LinToken`s, which in turn refers to the path in the tree. Therefore you need one `Linearization` per tree, which was what we wanted to get away from when moving from trees.  

`Test.Menu` behaves differently that the GUI, because when testing you define this function:

    getMenuFromStringRep :: Context -> String -> Menu

which parses to be able to create all possible `Linearization`s and then `foldMap` on each of the `Menu`s. This is a different behaviour than in the GUI.

This means that `LinToken` should not contain a path, because then we need several `Linearization`s for every string. 

What would have to change in the code for this?

**Comment by fredefox** [comment]
I'm not sure if we want to put `getMenuFromStringRep` in the core library, that's why I just put it in the test-module. It's definition is quite simple, so it's not like it's deviating a whole lot from the way it works in the GUI:

```
getMenuFromStringRep ctxt = foldMap (Menu.getMenu ctxt) . parseLin ctxt

parseLin ∷ Context → String → Set Linearization
parseLin ctxt = parseTree >>> map mkL >>> Set.fromList
  where
  parseTree ∷ String → [TTree]
  parseTree = Grammar.parseSentence grammar (Linearization.ctxtLang ctxt)
  mkL ∷ TTree → Linearization
  mkL = mkLinSimpl ctxt

```
Now that I'm working on the CLI, however, I will need something like this. So perhaps I will move it provisionally to `Muste.Menu.Internal`.

**Comment by heatherleaf** [comment]
That's ok with me. 

But there's a general problem, which got me to create this issue. The server should not communicate paths to the client (and vice versa), because paths imply a specific tree, but the client should be ignorant of which tree is meant. 

I.e., now the menus that are sent to the client contain paths (because `LinToken`) contain paths. E.g., "amicus bonus magnus est" is ambiguous with the following two `Linearization`:

    [ ([0,0,0,1,1,0], "amicus"), ([0,0,0,1,0,0], "bonus"), ([0,0,1,1,0], "magnus"), ([0,0,1,0], "est") ]
    [ ([0,0,0,1,1,1,0], "amicus"), ([0,0,0,1,0,0], "bonus"), ([0,0,0,1,1,0,0], "magnus"), ([0,0,1,0], "est") ]

The first corresponds to Swedish "en god vän är stor", and the second to "en god stor vän är". Which one of those is sent to the client? How about the menus: will the client treat the two as different linearisations?

So, how difficult would it be to change the interface between the server and client to *not* use paths in linearisations?

**Comment by fredefox** [comment]
Actually I think that we are not using the paths ATM. I think it's a simple matter of me not having had time to yank that data out of the representation yet. This is just my immediate hunch. A further investigation of this and more detailed answers to your questions will have to wait till tomorrow, however.

**Comment by fredefox** [comment]
Nvm the above "closes", that was a typo.

**Comment by fredefox** [comment]
There are some design decisions to be made here. I haven't had so much time to look at it today, unfortunately, so it's gonna be next week. `LinTokens` contains paths, and they need to for various reasons. For one thing I recently implemented

    selectionFromPath ∷ Path → Linearization → Selection

Which uses the paths.

**Comment by heatherleaf** [comment]
Yes, lots of design decisions. I will think about this over the weekend and try to suggest and explain with examples

**Comment by fredefox** [comment]
Sounds good. I'll mull it over as well. There are quite a lot of considerations.

**Comment by heatherleaf** [comment]
See #19 for ideas

**Comment by heatherleaf** [comment]
I think this is pretty much replaced by #19, so closing
