### ISSUE TITLE
CLI doesn't work for "Johan älskar vännen i Paris"

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#17]
When I set the sentence in `muste-cli` to "Johan älskar vännen i Paris", it shows no menus:

```
§ Johan älskar vännen i Paris
Sentence is now: Johan älskar vännen i Paris
§
```

It works fine for e.g., "Johan älskar vännen idag"

**Comment by fredefox** [comment]
I'm guessing this is because the sentence cannot be parsed with the given grammar.

**Comment by heatherleaf** [comment]
Nope, it's in the latest Exemplum grammar. And the final menu test: 

          DEL: i Paris:                                    FAIL (4.19s)
            test/Test/Common.hs:36:
            Testing: [Johan älskar vännen i Paris]  -->  [Johan älskar vännen]
             
            Expected to find one of:
            [ Johan älskar vännen ]
             
            Somewhere in the menu:
            [ Johan älskar vännen idag
            , Johan älskar vännen nu
            , Johan älskar vännen redan ]

The test fails, but the sentence is parsed and returns a menu for the selection [3,4]. Doesn't show anything in the CLI though.

**Comment by fredefox** [comment]
I don't get a menu for "Johan älskar vännen idag" either.

**Comment by heatherleaf** [comment]
Sorry, forgot to push my changes... Now in 0c6bf57f60c2e5e4671fa7094b567a6872e67f36

**Comment by fredefox** [comment]
Bueno. Will have a look.

**Comment by fredefox** [comment]
Can you try running gf directly and tell me if you get different output from me?

```
> i muste/data/gf/grammars/novo_modo/ExemplumSwe.gf
linking ... OK

Languages: ExemplumSwe
140 msec
Exemplum> parse "Johan älskar vännen i idag"
The parser failed at token 5: "idag"
20 msec
Exemplum> parse "Johan älskar vännen i Paris"
useS (useCl (simpleCl (usePN john_PN) (transV love_V (advNP (detCN theSg_Det (useN friend_N)) (prepNP in_Prep (usePN paris_PN))))))
useS (useCl (simpleCl (usePN john_PN) (advVP (transV love_V (detCN theSg_Det (useN friend_N))) (prepNP in_Prep (usePN paris_PN)))))

4 msec

```

**Comment by fredefox** [comment]
I can look into making the CLI reporting such errors if you want...

**Comment by heatherleaf** [comment]
Right, works for me too now. Strange, wonder what I did wrong before...
