### ISSUE TITLE
Debug options in the GUI and the CLI

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#20]
To be able to debug things better, it would be good with some "debugging mode" in the GUI and CLI. 

What I want is that the nodes are shown together with the sentence, including the menu items. I guess this means that the `NewFancyMenu` will have to use `Token.Annotated`, wo be able to show the nodes.

### The GUI

Something like this:

```
<span>flickan<sub class="debug">girl_N</sub></span>
<span>slår<sub class="debug">hit_V, switch_on_V</sub></span>
```

### The CLI

The CLI should show which words are selected for each menu, and show the nodes for each menu item. Something like this:

```
Sentence is now:  flickan slår på en dator    [girl_N  hit_V/switch_on_V  on_Prep/switch_on_V  aSg_Det  computer_N]

[0-0] <> flickan slår på en dator
<en> flicka slår på en dator                  [aSg_Det  girl_N  hit_V/switch_on_V  on_Prep/switch_on_V  aSg_Det  computer_N]
<många> flickor slår på en dator              [many_Det  girl_N  hit_V/switch_on_V  on_Prep/switch_on_V  aSg_Det  computer_N]

[0-1] <flickan> slår på en dator
<flickorna> slår på en dator                  [girl_N  hit_V/switch_on_V  on_Prep/switch_on_V  aSg_Det  computer_N]
<pojken> slår på en dator                     [boy_N  hit_V/switch_on_V  on_Prep/switch_on_V  aSg_Det  computer_N]
```

Even better if the nodes could be aligned to a specific column (e.g., 40 chars)

**Comment by fredefox** [comment]
We have something like this. You can create a bookmarklet with the following value for the URL:

```
javascript:(function () {
    var sheet = window.document.styleSheets[0];
    sheet.addRule('.debug', 'display: initial;');
})();
```

E.g. name it "debug". Then hit that button when you need to see the debug information.

Tested with Chrome. Should be cross-browser compliant though.

**Comment by fredefox** [comment]
I will not rule out the possibility that I have committed the dreaded one-off error in highlighting mechanism in the pretty-printer for the CLI. [Sample output](https://pastebin.com/raw/HMfRJ16V).

**Comment by fredefox** [comment]
One issue remains that since the menu returns unannotated linearizations we cannot display information about the internal nodes.

**Comment by fredefox** [comment]
*If* there is such a problem, the offending function is:

https://github.com/MUSTE-Project/MULLE/blob/787f348d766dbcc9760c312681778a607543e6f8/muste/app/Main.hs#L100-L104

**Comment by heatherleaf** [comment]
You're right about the menu containing unannotated lin's. But I think it's important to be able to see debug info in the CLI (and the GUI), when developing grammars and the algorithms.

So: is it possible to change the type for `NewFancyMenu`?

    newtype NewFancyMenu = NewFancyMenu (Map Selection (Set (Selection, Sentence.Linearization Token.Annotated)))

`Ajax.ClientTree` should still use unannotated linearizations.

**Comment by fredefox** [comment]
It looks like you fixed points 1 and 2 yourself. Is there anything left in this ticket besides #3?

**Comment by heatherleaf** [comment]
no, pretty much works as I want now - but my code is ugly...

**Comment by fredefox** [comment]
Bullet 3 resolved in 06a183dcc2a5c85028750c7b2d0168db98c64e16

**Comment by fredefox** [comment]
Was there something missing for the web UI related to this or can I close?

**Comment by heatherleaf** [comment]
Nope, looks fine!
