### ISSUE TITLE
Selections don't show correct in the web UI

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#22]
Here are each menu from the CLI, followed by how it looks in the web UI (for the Prima grammar and the sentence "vinet är vist"). As you can see, both the red selection and the bold replacement are out of sync.

### Selection 0-1: problem
Here the UI selects 0-2 instead of 0-1 as it should be
```
{0-1}: [ vinet ] är vist
[ Afrika ] är vis
[ Augustus ] är vis
[ Gallien ] är vis
[ fadern ] är vis
...
```
![image](https://user-images.githubusercontent.com/1324196/44990419-3c349d80-af91-11e8-8ef5-dbcdc09e1873.png)

### Selections 1-3 and 2-3: correct

```
{1-3}: vinet [ är vist ]
vinet [ säger ]
vinet [ besegrar Afrika ]
vinet [ besegrar Augustus ]
vinet [ besegrar Gallien ]
...
```
![image](https://user-images.githubusercontent.com/1324196/44990479-6a19e200-af91-11e8-9e8f-adbf09b72fc3.png)

```
{2-3}: vinet är [ vist ]
vinet är [ besegrat ]
vinet är [ enormt ]
...
```
![image](https://user-images.githubusercontent.com/1324196/44990488-72721d00-af91-11e8-94c7-36a7685953d5.png)

### Insertions: don't work yet
Insertions are not implemented in the UI yet, but instead they show up as strange replacements.

```
{0-0}: [ ] vinet är vist
[ ett ] vin är vist
[ många ] viner är visa
[ det besegrade ] vinet är vist
[ det enorma ] vinet är vist
...
```
Note that only "det" is emphasized, not "det besegrade":
![image](https://user-images.githubusercontent.com/1324196/44990269-cf210800-af90-11e8-9bee-88b878c1eaa7.png)

```
{1-1}: vinet [ ] är vist
vinet [ Afrika ] är vist
vinet [ Augustus ] är vist
vinet [ Gallien ] är vist
```
This one is correct, except the selection:
![image](https://user-images.githubusercontent.com/1324196/44990466-61291080-af91-11e8-82d5-683a24e31ded.png)

```
{0-1,2-2}: [ vinet ] är [ ] vist
[ ofta ] är [ vinet ] vist
```
This is perhaps a special case, but both the selection and the emphasis are strange:
![image](https://user-images.githubusercontent.com/1324196/44990452-58d0d580-af91-11e8-8914-55d1b6425dd7.png)

**Comment by fredefox** [comment]
Some times the fix is literrally a one character fix:

```
commit f143c74faca3e7c0d7003fd02a78e879a6b9be56 (HEAD -> fredefox, origin/fredefox)
Author: Frederik Hanghøj Iversen <fhi.1990@gmail.com>
Date:   Tue Sep 4 10:27:32 2018 +0200

    Issue #22: Fix one-off in highlighting


diff --git a/muste-ajax/static/muste-gui.js b/muste-ajax/static/muste-gui.js
index 59a4e33..71b6a6a 100644
--- a/muste-ajax/static/muste-gui.js
+++ b/muste-ajax/static/muste-gui.js
@@ -509,7 +509,7 @@ function is_selected(sel, idx) {
         var a = intval[0];
         var b = intval[1];
         if(i < a) return false;
-        if(i > b) return false;
+        if(i >= b) return false;
         return true;
     }
     for(var intval of sel) {
```

**Comment by fredefox** [comment]
I believe I've fixed all except insertions. I asked for clarification in #2 because I don't fully understand the specification. I have an idea for a first approximation, so I'll start building up the scaffolding to get this to work.

**Comment by heatherleaf** [comment]
one-character fixes are the best :)

One thing remaining: the order of the selections is not the best. When selecting the Prima lesson, and click "vis", I first get:

![image](https://user-images.githubusercontent.com/1324196/45022851-866f5a80-b035-11e8-967b-e41fd1c83e67.png)

and clicking on "vis" again gives this:

![image](https://user-images.githubusercontent.com/1324196/45022866-9129ef80-b035-11e8-9580-e3cdde5c5746.png)

The second menu should be the first.

**Comment by fredefox** [comment]
Which sentence is that?

**Comment by fredefox** [comment]
The menus are iterated in the same order as they show up in muste-cli.

**Comment by heatherleaf** [comment]
Aha! Then the ordering between selections must change: the menu should be ordered by the "size" of the selection. I guess like this:

    size sel = sum [ k-j | (j,k) <- sel ]

(If two selections have the same size, then it doesn't matter which comes first)

**Comment by fredefox** [comment]
I'm just supplying some implementation detail context here; The menus are seralized according to the `ToJSON` instance for `NewFancyMenu` which just first converts the outter `Map` to `[]` via `Map.toList`. `Map.toList` used the `Ord` instance of the keys. Effectively the order will correspond to the the `Ord` instance for `Selection`s.

The list that is sent over the wire is converted to a ECMAScript 6(?) map-object. However, we don't really use it, since we convert it back into a list when we iterate through it to find the "valid" menus.

**Comment by fredefox** [comment]
> Then the ordering between selections must change: the menu should be ordered by the "size" of the selection.

This is why I've been very liberal in my usage of newtypes throughout the implementation, because we want a selection to be *like* `[(Int, Int)]` but with a different `Ord` instance, and with ... and with ...

**Comment by fredefox** [comment]
Can you give 94e9c0f a spin? I couldn't find the example sentence that you mentioned. I've created a new-type for selections and intervals with the desired `Ord` instance.

**Comment by fredefox** [comment]
The relevant change is:

```
instance Ord Interval where
  a `compare` b = case size a `compare` size b of
    EQ → runInterval a `compare` runInterval b
    x  → x
    where
    size ∷ Interval → Int
    size (Interval (i, j)) = i - j
```

We first order intervals by their `size` and if they are equal we just use the `Ord` instance for `(int, Int)` (probably pair-wise ordering).

**Comment by fredefox** [comment]
Whoopsie! Please give 29a5954 a spin in stead.

**Comment by fredefox** [comment]
I still don't think this is what you want. I only changed the `Ord` instance for `Interval` and reused this instance for `Selection`s (`Coercible Selection [Interval]`):

```
instance (Ord a) => Ord [a] where
    compare []     []     = EQ
    compare []     (_:_)  = LT
    compare (_:_)  []     = GT
    compare (x:xs) (y:ys) = case compare x y of
                                EQ    -> compare xs ys
                                other -> other
```

But this is not what you want.

**Comment by heatherleaf** [comment]
More like this:
```
instance Ord Selection where
    Selection a `compare` Selection b = case size a `compare` size b of
            EQ => a `compare` b
            cmp => cmp
        where size ints = sum [ k-j | Interval (j,k) <- ints ]
```

**Comment by heatherleaf** [comment]
looks good now!
