### ISSUE TITLE
Incorrect, spurious and missing menu items

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#24]
There are some remaining problems with the creation of menus. Probably they have different causes, but here I write down several examples where it goes wrong.

### Examples for "flickan slår på en dator"

The following menu should be for selection `{0-1}`:
```
{}: flickan slår på en dator
flickan slår på en dator
flickor slår på en dator
flickorna slår på en dator
```
The problem is that all sentences have the same nodes. It's a difficult problem, I have to think about it. Worth an issue of its own
- also note that the original sentence shows up here -- it shouldn't

----
The following is correct:
```
{1-1}: flickan [ ] slår på en dator
...
```
- but it should also contain the items `flickan [i huset] slår...`, and `flickan [och pojken] slår...` (etc)
- and the {0-0} insertion menu should contain: `[] flickan...` --> `[pojken och] flickan...`

----
None of the following menu items should be suggested:
```
{1-2}: flickan [ slår ] på en dator
flickan [ läser Johan ] på en dator
flickan [ läser Paris ] på en dator
flickan [ läser blå ] på en dator
flickan [ läser dem ] på en dator
flickan [ läser det ] på en dator
(...)
flickan [ stänger Johan ] på en dator
flickan [ stänger Paris ] på en dator
flickan [ stänger blå ] på en dator
(...)
flickan [ älskar Johan ] på en dator
flickan [ är Johan ] på en dator
flickan [ slår dem sönder ] på en dator
(...)
```
- they should be removed because you can get there in two shorter steps: 
    1. `flickan [slår] på...` --> `flickan [läser] på...`
    2. `flickan läser [] på...` --> `flickan läser [Johan] på...`

-----
None of the following menu items should be suggested:
```
{1-5}: flickan [ slår på en dator ]
flickan [ läser ]
flickan [ slår ]
flickan [ stänger ]
flickan [ älskar ]
flickan [ är ]
flickan [ slår sönder ]
flickan [ läser blå ]
flickan [ läser dålig ]
flickan [ läser god ]
(...)
flickan [ slår blå ]
flickan [ stänger blå ]
flickan [ älskar blå ]
flickan [ är blå ]
flickan [ slår sönder blå ]
(...)
```
- `flickan [slår]` and `flickan [slår blå]` should be menu items, but for the selection {2-5}: 
    - `flickan slår [på en dator]` --> `flickan slår []`
    - `flickan slår [på en dator]` --> `flickan slår [blå]`
- the rest should not be suggested at all, because you can get there in two shorter steps: 
    1. `flickan [slår] på...` --> `flickan [läser] på...`
    2. `flickan läser [på en dator]` --> `flickan läser [blå]`

---
These menu items are correct, but too few:
```
{2-2}: flickan slår [ ] på en dator
flickan slår [ idag ] på en dator
flickan slår [ nu ] på en dator
flickan slår [ redan ] på en dator
```
- there should also be `...slår [Paris] på...`, and `...slår [dem] på...`, and `...slår [boken] på...`

---
This looks a bit strange, but I guess it's ok. The reason is that the grammar says that the particle verb "slår på" should have an object pronoun ("henne") inbetween, but other object noun phrases ("en dator") after. I would say that the grammar is a bit strange here.
```
{2-2,3-5}: flickan slår [ ] på [ en dator ]
flickan slår [ dem ] på [ ]
flickan slår [ det ] på [ ]
flickan slår [ henne ] på [ ]
flickan slår [ honom ] på [ ]
```

----
Ok, but too few suggestions:
```
{2-5}: flickan slår [ på en dator ]
flickan slår [ ]
flickan slår [ idag ]
flickan slår [ nu ]
flickan slår [ redan ]
```
- should include `...slår [henne]`, etc
- also `...slår [en dator]`, but this should rather be for another selection: 
    - {2-3}: `flickan slår [på] en dator` --> `flickan slår [] en dator`
    - and the other direction, {2-2}: `flickan slår [] en dator` --> `flickan slår [på] en dator`

----
Also ok:
```
{3-4}: flickan slår på [ en ] dator
flickan slår på [ ] datorer
flickan slår på [ ] datorerna
flickan slår på [ ] datorn
flickan slår på [ många ] datorer
```
- perhaps the deletions should be `...på [en dator]` --> `...på [datorer]`, but I'm not at all sure.

---
Also ok, but too few items:
```
{5-5}: flickan slår på en dator [ ]
flickan slår på en dator [ Johan ]
flickan slår på en dator [ Paris ]
flickan slår på en dator [ idag ]
flickan slår på en dator [ nu ]
flickan slår på en dator [ redan ]
```
- it should also contain the items `...en dator [i huset]`, and `en dator [och pojken]` (etc)
- and the {3-3} insertion menu should contain: `...slår på [] en dator` --> `...slår på [pojken och] en dator`

**Comment by heatherleaf** [comment]
Some of the examples are probably because there is some problems with the algorithms themselves, and some are because of a bug in the implementation. So, it falls on both @heatherleaf and @fredefox

**Comment by fredefox** [comment]
> they should be removed because you can get there in two shorter steps

The logic for this was in the now deprecated `Muste.Menu.Interrnal` module. So I suppose this should just be ported over.

**Comment by heatherleaf** [comment]
How about splitting `Muste.Menu.New.getMenuItems` into two parts? First we collect all substitution pair in a large collection. I.e., these lines: 

https://github.com/MUSTE-Project/MULLE/blob/52e5f265ed87b3ee49006b9fa0a822c06d9e0aae/muste/src/Muste/Menu/New.hs#L177-L181

into a function:

    collectTreeSubstitutions :: Context -> String -> Set TreeSubst
    type TreeSubst = (XTree, XTree)
    type XTree = (TTree, [Tokn], [Node])

then call a filtering function, which is a version of `Muste.Prune.onlyKeepCheapest`:

    filterTreeSubstitutions :: Set TreeSubst -> Set TreeSubst

then the final lines from `getMenuItems`:

https://github.com/MUSTE-Project/MULLE/blob/52e5f265ed87b3ee49006b9fa0a822c06d9e0aae/muste/src/Muste/Menu/New.hs#L182-L189

as a function: 

    collectMenuItems :: Set TreeSubst -> Set (Selection, Set (Selection, Linearization))

Final collection something like this:

    getMenuItems :: Context -> String -> NewFancyMenu
    getMenuItems ctxt str = collectTreeSubstitutions ctxt str & filterTreeSubstitutions & collectMenuItems & fromListWith union & NewFancyMenu

(not tested, so caveats)

**Comment by heatherleaf** [comment]
Now I've implemented filtering in branch `filter-menu`, commit 8d2d65741a767e45535c83fc288a4c822e2fd821

The number of menu items for "flickan slår på en dator" are reduced from 265 to 159. 

Unfortunately, the running time does not change: at least 95% of the time is spent in `collectTreeSubstitutions`. (I'm not good at profiling, so I don't know yet where most of the time goes)

**Comment by fredefox** [comment]
How did you find out that it spends 95% of the time there, then?

**Comment by fredefox** [comment]
As far as I can see the supremely biggest problem is in `Muste.Prune.guardHeuristics`. Specifically the bit where we want to test if the functions in the one tree is disjoint from the tree in the other. This forces us to traverse the whole tree. I suppose that such a traversal shouldn't be a big problem as long as the trees aren't too big. So maybe the problem really is that we're generating a huge amount of trees that will anyways be filtered out.

**Comment by heatherleaf** [comment]
How I found out? I'd rather not say, it will make me look stupid... 

(I timed the total execution time, with and without calling `filterTreeSubstitutions`, and noticed no difference at all)

**Comment by fredefox** [comment]
Hehe :D okidoki :D

I just want to point out that laziness can really play tricks on you so such a test can be hiding a different problem.

It feels like it's running a lot smoother now. I found another easy improvement in 7fcd17bc1a76c7b7bfb0b8bd8bd2969f4e6cd9a9

**Comment by heatherleaf** [comment]
The main problem is the number of adjunction trees per category. Here are the figures for the ExemplumSwe grammar:

    [("A",6),("AP",7),("Adv",392),("CN",21),("Cl",8606),("Conj",3),("Det",6),("N",10),("NP",104),("PN",3),("Prep",4),("Pron",5),("S",8607),("Utt",98867),("V2",8),("VP",1265)]

Not enormous for most categories, but close to 100,000 adj.trees for `Utt`. That's the top-level category, so all trees contain one `Utt` tree. 

`Prune.simTrees` will therefore be called once with the toplevel tree and 100,000 adj.trees (argument `adjTreesForCat`). Then `Prune.pruneTree` is called with the toplevel tree, and returns 15 different pruned trees. 

https://github.com/MUSTE-Project/MULLE/blob/2a9b67811d53b4817bb0003bb430fbb59edd460b/muste/src/Muste/Prune.hs#L176-L181

Each of the 15 pruned trees is then compared with all 100,000 adj.trees (`filterTrees`), meaning ca 1.5m calls to `guardHeuristics`.

https://github.com/MUSTE-Project/MULLE/blob/2a9b67811d53b4817bb0003bb430fbb59edd460b/muste/src/Muste/Prune.hs#L184-L189

I have an idea how to reduce the nr of adj.trees, just give me an hour to formulate myself.

**Comment by heatherleaf** [comment]
We use the following, requiring that `pruned` and `pruned'` (where `pruned'` comes from the 100,000 adj.trees) have exactly the same metas:

https://github.com/MUSTE-Project/MULLE/blob/2a9b67811d53b4817bb0003bb430fbb59edd460b/muste/src/Muste/Prune.hs#L213-L216

The metas in an adj.tree is static information, so it should be possible to optimise `AdjunctionTrees` quite a bit. Now it's a `Map Category [TTree]`, where the `TTree`s are the adj.trees for the given category. 

```
-- belongs to `Muste.AdjunctionTrees.Internal`
-- invariant: and [ c == topNode t && length m == length (filter isMeta (flatten t)) | 
--                  (c,innermap) <- toList adjtrees, (m,ts) <- toList innermap, t <- ts ]
newtype AdjunctionTrees
      = AdjunctionTrees (Map Category (Map Metas [TTree]))

 -- invariant: this should rather be a bag, which we can implement as an ordered list
type Metas = [Category]

-- invariant: length metas == length branches
-- invariant: length (filter isMeta (flatten pruned)) == length metas
pruneTree :: TTree -> [(TTree, Metas, [TTree])]
pruneTree tree = [ (pruned, metas, branches) | ... ]

simTrees :: Map Metas [TTree] -> TTree -> [SimTree]
simTrees adjTreesForCat tree = do
  (pruned, metas, branches) <- pruneTree tree
  pruned' <- filterTrees (adjTreesForCat `lookup` metas) pruned
  tree'   <- insertBranches branches pruned'
  pure (tree `treeDiff` tree', tree', pruned, pruned')
```

Now `guardHeuristics` can get rid of the choices `PRUNE_ALT_2A` and `PRUNE_ALT_2B`

Was that clear enough?

**Comment by heatherleaf** [comment]
`Muste.AdjunctionTrees.getAdjunctionTrees` also has to be updated of course, which is nontrivial. Now the internal `go` function has type

    go :: Category -> (Category, [TTree])

which has to change to 

    go :: Category -> (Category, Map Metas [TTree])

**Comment by heatherleaf** [comment]
hmm... these comments really should belong to #23 -- is there a way to move them there and close this issue?

**Comment by fredefox** [comment]
In general I must say this is a quite difficult task. There are so many directions to go in. But as for the case where the girl hits the computer it looks like the fault is not with muste. I just ran the profiler thus:

    muste-cli +RTS -p -RTS "pigen slår på en dator"

I'm guessing you did something like:

    time muste-cli "pigen slår på en dator"

[This is the output from the profiler](https://pastebin.com/raw/KwVVc12L). As can be seen 90% of the time is spent doing `PGF.parsePGF`. This is a function I implemented and kindly asked to have added to the public facing API of `pgf`. They've implemented their own API for binary data. Perhaps I erred in my implementation of `parsePGF` - perhaps there's something else going on... Will keep investigating.

**Comment by heatherleaf** [comment]
Reading the PGF is a one-time thing. What I did was calling `getCPUTime` in different places in `Main.updateMenu`. Then I run `muste-cli` and give the example sentence. It takes ~10 secs to create the menu. Next I give the same sentence and it still takes ~10 secs. 

I assume that `parsePGF` is called only once, so the time it takes to read the PGF should be negligble.

**Comment by heatherleaf** [comment]
This is how I've modded the cli:

```
updateMenu ∷ String → Repl ()
updateMenu s = do
  ctxt ← getContext
  m ← getMenuFor s
  liftIO $ timeCommand "Update menu" $ do
    putStrLn $ "Sentence is now: " <> s
    putDocLn $ prettyMenu ctxt s m
  setMenu m

timeCommand :: String -> IO a -> IO a
timeCommand title cmd = do
    time0 <- getCPUTime
    result <- cmd
    time1 <- getCPUTime
    let secs :: Float = fromInteger (time1-time0) * 1e-12
    printf "\n>>> %s: elapsed time %.2f s <<<\n\n" title secs
    return result
```

**Comment by heatherleaf** [comment]
I really think that changing the `AdjunctionTrees` to a `Map Category (Map Metas [TTree])` will help a lot. Instead of 15 x 100,000 calls to `guardHeuristics`, I suspect there will be 5 x 10,000 or similar.

**Comment by fredefox** [comment]
You say it's a one-time thing, yet the profiler reveals that we spend 90% of our time doing it.

With 1e1613b7aca4b2974e3b972c086809f010e0d301 I've managed to get the same invocation down to 1.67s. [Full profiler output](https://pastebin.com/raw/dqQy8yuM).

There are probably still room for improvement in some places.

**Comment by fredefox** [comment]
You say it's a one-time thing, yet the profiler reveals that we spend 90% of our time doing that thing.

**Comment by fredefox** [comment]
I dun goofed. I forgot that "pige" is not Swedish. This is the summary from the profiler output with the correct sentence:

```
	Wed Sep 12 16:14 2018 Time and Allocation Profiling Report  (Final)

	   muste-cli +RTS -p -RTS flickan slår på en dator

	total time  =       14.01 secs   (14008 ticks @ 1000 us, 1 processor)
	total alloc = 24,748,854,032 bytes  (excludes profiling overheads)

COST CENTRE                 MODULE                 SRC                                              %time %alloc

areDisjoint                 Muste.Common           src/Muste/Common.hs:(86,1)-(88,12)                20.5   17.3
getFunctions                Muste.Grammar.Internal src/Muste/Grammar/Internal.hs:(211,1)-(213,21)    18.6   33.1
getFunctions.getF           Muste.Grammar.Internal src/Muste/Grammar/Internal.hs:(212,11)-(213,21)   15.9   35.2
compare                     Muste.Grammar.Internal src/Muste/Grammar/Internal.hs:47:47-49            15.8    0.0
>>=.\                       Data.Binary.Get        Data/Binary/Get.hs:(125,28)-(126,54)              11.0    1.1
compare                     Muste.Tree.Internal    src/Muste/Tree/Internal.hs:136:13-15               3.7    0.0
<                           Muste.Grammar.Internal src/Muste/Grammar/Internal.hs:47:47-49             2.9    0.0
>=                          Muste.Grammar.Internal src/Muste/Grammar/Internal.hs:47:47-49             1.5    0.0
getMetas.getMetas'          Muste.Grammar.Internal src/Muste/Grammar/Internal.hs:(206,11)-(207,71)    1.1    1.6
process                     PGF.Parse              PGF/Parse.hs:(276,1)-(413,96)                      1.0    0.6
getMetas                    Muste.Grammar.Internal src/Muste/Grammar/Internal.hs:(205,1)-(207,71)     0.5    1.1
editDistance.oneDiag.doDiag Muste.Common           src/Muste/Common.hs:(112,21)-(115,91)              0.5    1.7

```

pastebin does not like the idea of me uploading a 1MB file...

**Comment by fredefox** [comment]
There's an issue with using profiling+template-haskell. But fret not! Here's a work-around:

Do this once:
```
stack build --work-dir .stack-work-prof
find .stack-work-prof -name stack-build-caches -exec rm -rf {} \;
```

Do this on every subsequent build *when you want profiling*:

```
stack install  --ghc-options="-osuf p_o" --profile --work-dir .stack-work-prof
```

Make sure to only request a build against `.stack-work-prof` when you're building with profiling and vice versa - i.e only build against `.stack-work` when you don't need it.

The commands are off the top of my head. Let me know if you encounter any problems.

**Comment by heatherleaf** [comment]
Thanks, I'll try that. 

Closing this issue now -- we've digressed into #23, so let's continue the discussion there.
