### ISSUE TITLE
Debug information in CLI

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#26]
I'd like to improve the CLI, so that it can be used as a grammar debugging tool. Here are some things I'd like to see (syntax is of course discussable).

Precompute the adjunction trees to an external file. This should load `Exemplum.pgf`, precompute the adjunction trees, and save a binary representation in `Exemplum.adjtrees` (or something like that):

    $ muste-precompute --grammar=.../Exemplum

Specify the grammar from the command line. This should load `Exemplum.pgf` and `Exemplum.adjtrees` and start the CLI:

    $ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe

Run one sentence and exit:

    $ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe "flickan slår på datorn"

This (and specifying a sentence in the CLI) should calculate and print all menus (as now).

(The `:sel` command in the CLI is not necessary)

**Comment by heatherleaf** [comment]
Here are some additional debugging options I'd like to see. I'll explain further in separate issues.

- Showing the menus in "compact" form (only print the n:o of menu items in each menu):

        $ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe --compact

- Setting the max size of adjunction trees and pruned trees:

        $ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe --maxsize=20

- Printing the size of the pruned tree and its replacement adjunction tree, for each menu item:

        $ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe --printsize

- Printing the number of trees in different stages of filtering:

        $ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe --printfilter

- And anyhing else that you think would be useful

It's ok to let the debugging options work only if compiled with `--ghc-options="-DDEBUG"`, if they might slow down things.

**Comment by heatherleaf** [comment]
And another one:
- Show the linearisations with grammar node information:

        $ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe --printnodes

    Explanations in a separate issue.

**Comment by fredefox** [comment]
Perhaps the `muste-precompute` could be implemented as

1. A command line option to `muste-cli`
2. A command in the interactive mode

Rather than as a seperate binary. What do you think?

Or it could even be a sub-command to `muste-cli`. Then it would behave like a separate binary as you wanted. If you're familiar with the CLI for `git`, then that's how it works:

```
git commit
git rev-parse
git fetch
```

Are all examples of sub-commands.

**Comment by heatherleaf** [comment]
I’m fine with any of those three. Whatever is easiest to implement.

**Comment by heatherleaf** [comment]
Now I've created sub-issues for everything I asked for...
