### ISSUE TITLE
CLI: print the size of the pruned tree

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#29]
Sub-issue to #26: Print the size of the pruned tree and its replacement adjunction tree, for each menu item. Something like this:

```
$ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe --printsize "flickan slår på en dator"

Sentence is now: flickan slår på en dator

{0-0}: [ ] flickan slår på en dator                          size:  pruned  replacement
[ en ] flicka slår på en dator                                        1          1
[ många ] flickor slår på en dator                                    1          1
[ den stora ] flickan slår på en dator                                0          3

{0-1}: [ flickan ] slår på en dator                          size:  pruned  replacement
[ Johan ] slår på en dator                                            4          2
[ Paris ] slår på en dator                                            4          2
...
```

For the menu item "[ många ] flickor ...", this would mean the following:
- the pruned tree is `(theSg_Det)`, which has size 1
- the replacement is `(multus_Det)`, which has size 1

For the menu item "[ den stora ] flickan ...", this would mean:
- the pruned tree is `?CN` (i.e., nothing is removed)
- the replacement is `(attribCN (useA (big_A)) ?CN)`, which has size 3

And for "[ Johan ] slår på ...", this would mean:
- the pruned tree is `(detCN (theSg_Det) (useN (girl_N)))`, which has size 4
- the replacement is `(usePN (john_PN))`, which has size 2

**Comment by fredefox** [comment]
I'm not clear on how you want to implement this. It doesn't seem like this information is recoverable from a `Menu`. Do you want to extend `getMenu` to also generate this information?

**Comment by heatherleaf** [comment]
Yes, probably we have to extend `getMenu` to be able to solve this. I'm not sure it's needed right now, so I'be put it on hold.

**Comment by heatherleaf** [comment]
Closing this, it's not that necessary
