### ISSUE TITLE
Change representation from single tree to sets of trees.

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#3]
Multiple sentences can have the same linearized
representation. Therefore one linearization must be associated with
one or more abstract representations.

**Comment by fredefox** [comment]
Quoting from the above commit:

Model the relationship between `stree` as a general
relationship (i.e. not functional).  This is in adressing issue #3:
"Change representation from single tree to sets of trees".  The
challenge of course is that Haskell is a functional language (duh)
and so don't model relational data as easily.  This [SO post] has
some nice insightful comments.  In particular a library `ixset` is
mentioned.  Going down that path would requre yanking out the
fields and replacing them with another field `treeToken` (better
naming suggestions are welcome) this field should act just as a
many-to-many relationship is modelled in a relational database.  Of
course all this complexity can be hidden (at least in the Haskell
source) by making the type of `treeToken` abstract.  Similarly, if
we at some point transition to another framework for the fron-end
code we could write a wrapper around this functionality.  A risk
here if we use a library (like e.g. `isxset`) is how much work is
needed to replicate similar functionality for the serialized data.

[SO post]: https://stackoverflow.com/questions/9234205/safe-modelling-of-relational-data-in-haskell****

**Comment by fredefox** [comment]
I guess I should make doubly sure I understand the requirement correctly here. @heatherleaf Have I understood it correctly that multiple trees should be associated with multiple linearizations *and* that multiple linearizations can be associated with multiple trees?

**Comment by heatherleaf** [comment]
Damn, why isn’t my comment formatted? Difficult to edit on the phone...

**Comment by fredefox** [comment]
I think it might be useful to first merge `Linearization` and `[LinToken]` into one data-type.

**Comment by heatherleaf** [comment]
Yes, it will interfere with #2 , and yes, merging linearisation types is a good idea. 

It’s probably best to do #2 and this (#3) in sequence. Don’t know which is best to start with.

**Comment by heatherleaf** [comment]
Perhaps it’s better to start with this, because there are less open questions here

**Comment by heatherleaf** [comment]
Sorry, I don't really understand. But I tried to look into the different trees that are sent around: 

    data ServerTree = ServerTree { slanguage :: String, trees :: Map LinTokens TTree, smenu :: Menu }
    data ClientTree = ClientTree { clanguage :: String, ctree :: Map LinTokens TTree }
    newtype Menu = Menu (Map Path [[CostTree]])
    data CostTree = CostTree { _cost :: Int, _lin :: [Linearization], _tree :: TTree }

### Minor stuff

A minor detail (which really has nothing to do with this issue), is that `[[CostTree]]` in `Menu` should probably be replaced by `[CostTree]`. The original reason for having an outer list was that it should be possible to split a menu into several menus if it was too long, but I now think that that should probably be decided in the frontend instead (it's the frontend that knows how many menu items can be displayed at the same time). 

    newtype Menu = Menu (Map Path [CostTree])

Another minor detail is that `Linearization` is misleading, since it's `[Linearization]` that is the real linearisation... But there is another goal to merge `LinToken` with `Linearization`, and then we can use `LinTokens` (or even `Linearization` for `[LinToken]`).

### Sets of trees

The main idea is to change every occurrence of `TTree` into a set. E.g., like this:

    newtype TTreeSet = TTreeSet [TTree]

### Server, client trees

I'm not sure that a `Map LinTokens TTree` is what you want? As I understand the workings, the server sends two `ServerTree`s to the client, one for each language. One `ServerTree` should therefore only have one linearisation (`LinTokens`). How about this type definition instead?

    data ServerTree = ServerTree { slanguage :: String, stokens :: LinTokens, strees :: TTreeSet, smenu :: Menu }

The `ClientTree` could be the same (but without the menu).

### Menu items

The `CostTree` is one menu item, which in turn should contain a linearisation and a tree set. And why not simply use `LinTokens` here as well: 

    data CostTree = CostTree { _cost :: Int, _lin :: LinTokens, _tree :: TTreeSet }

(The `_ltmatched` label in `LinToken` can simply be an emplty list, since it's not used in the CostTree: yes I know that's a bit like cheating...)

### Comparing trees

Also: you're finished when *one* srctree is equal to *one* target tree, not when all trees are the same (line 232 in Protocol.hs). Here's why:

- assume src = "the fish" (number ambiguity, giving two trees `(DetCN theSg fish)` and `(DetCN thePl fish)`)
- but dest = "fisken" (no number ambiguity, so one tree only `(DetCN theSg fish)`)
- then this should pass as a success

Something like this:

    compareTTreeSets :: TTreeSet -> TTreeSet -> Bool
    compareTTreeSets as bs = any [ a == b | a <- as, b <- bs ]

**Comment by fredefox** [comment]
* Replacing `[[CostTree]]` `[CostTree]`

I've noticed this. I'll do this refactor separately from this issue once this is resolved - just so it's easier to see where any potential regressions may come from. Should be easy to fix though.

* Sets of trees

I've fixed this now. I've put the changes in yet another branch [`wip/3-multiple-trees-2`](https://github.com/MUSTE-Project/MULLE/tree/wip/3-multiple-trees-2). I'll squash this all into one commit once I feel more confident about it and then clean up after my self (deleting these branches) I'm just putting it up here in case you're eager to have a look.

This representation was much, much easier to deal with. I still have some things that I wan't to double check however before I merge this in.

* Comparing `ClientTree`s

I've addressed this in b7e5a971e46a0388287b0eb89434b9706b76b1db.

* `LinTokens` and `Linearization`

I'd like to address this seperately as well.

**Comment by fredefox** [comment]
I've updated the [backlog] on `wip/3-multiple-trees-2` with the last outstanding challenge (as far as I can tell).

[backlog]: https://github.com/MUSTE-Project/MULLE/blob/e1d9be480096987cf674e49b3aff61beed721ea2/BACKLOG.md#issue-3-change-representation-from-single-tree-to-sets-of-trees

**Comment by fredefox** [comment]
I'm closing this in with [`0.2.0.3`](https://github.com/MUSTE-Project/MULLE/releases/tag/0.2.0.3). The thing I mentioned in the previous comment I decided is something I will not address as per [this comment](https://github.com/MUSTE-Project/MULLE/blob/0.2.0.3/muste-ajax/src/Protocol.hs#L315).

Please note that I still haven't actually tested this in a case where a tree has multiple linearizations. Given that Javascript lacks a (proper) type system I wouldn't be surprised if I've missed something. Let's reopen this once we find those errors. C.f. #8.

**Comment by fredefox** [comment]
I've also changed `Menu`s to map to `[CostTree]` in stead of `[[CostTree]]` - again, the most likely place that there may be regressions is in the front-end. However, I think this is unlikely. The change is introduced in [`0.2.0.4`](https://github.com/MUSTE-Project/MULLE/releases/tag/0.2.0.4)

**Comment by fredefox** [comment]
I have also gotten rid of the deprecated `Linearization`. Please see [`0.2.0.5`](https://github.com/MUSTE-Project/MULLE/releases/tag/0.2.0.5).

**Comment by heatherleaf** [comment]
To test if it works, you can change the Prima Latin grammar. Currently `PrimaRulesLat.gf` looks like this:

```
--# -path=latin-rgl/api:latin-rgl:.
concrete PrimaRulesLat of PrimaRules = CatLat ** PrimaRulesI-[useCNdefsg,useCNindefsg,useCNindefpl]
  with (Cat=CatLat), (Syntax=SyntaxLat), (Extra=ExtraLat), (Conjunction=ConjunctionLat) **
  open ResLat in {
lincat
  CS = Str ;
lin
    useCNdefsg cn = let q : Det = lin Det {s = \\_,_ => "" ; sp = \\_,_ => "(definite)" ; n = Sg } in lin NP (mkNP (q | theSg_Det) (lin CN cn)) ;
    useCNindefsg cn = let q : Det = lin Det {s = \\_,_ => "" ; sp = \\_,_ => "(indefinite)" ; n = Sg } in lin NP (mkNP (q | aSg_Det) (lin CN cn)) ;
    useCNindefpl cn = let q : Det = lin Det {s = \\_,_ => "" ; sp = \\_,_ => "(indefinite)" ; n = Pl } in lin NP (mkNP (q | aPl_Det) (lin CN cn));
    --    ppartAP v2 = PastPartAP (lin VP (mkVPSlash (lin V2 v2)));
    useS s = combineSentence s ! SPreO ! PreV ! SOV ;
}
```

Try to remove the special definitions for `useCN...`, lite this (I hope this works):

```
--# -path=latin-rgl/api:latin-rgl:.
concrete PrimaRulesLat of PrimaRules = CatLat ** PrimaRulesI
  with (Cat=CatLat), (Syntax=SyntaxLat), (Extra=ExtraLat), (Conjunction=ConjunctionLat) **
  open ResLat in {
lincat
  CS = Str ;
lin
    --    ppartAP v2 = PastPartAP (lin VP (mkVPSlash (lin V2 v2)));
    useS s = combineSentence s ! SPreO ! PreV ! SOV ;
}
```

Now, both "fienden besegrar Afrika" and "en fiende besegrar Afrika" will have the same Latin translation: "hostis Africam vincit"

    useS (useCl (simpleCl (useCNdefsg (useN hostis_N)) (transV vincere_V2 (usePN Africa_PN))))
    useS (useCl (simpleCl (useCNindefsg (useN hostis_N)) (transV vincere_V2 (usePN Africa_PN))))

**Comment by fredefox** [comment]
I've managed to build the executable `gf`. If I do

     gf PrimaRulesLat.gf

With your proposed patch I get

    File Cat.gf does not exist.
    searched in: ./
             /home/fredefox/workspace/MUSTE-Project/Mulle/muste-ajax/data/gf/grammars/novo_modo


And since `git ls-files | grep Cat.gf` gives me nothing I suppose I should find this elsewhere. [`gf-contrib`](https://github.com/GrammaticalFramework/gf-contrib) maybe?

**Comment by fredefox** [comment]
[`gf-rgl`](https://github.com/GrammaticalFramework/gf-rgl) was the ticket.

**Comment by fredefox** [comment]
After installing that I'm getting

    File SyntaxLat.gf does not exist.
    searched in: ./
             /home/fredefox/workspace/MUSTE-Project/Mulle/muste-ajax/data/gf/grammars/novo_modo
             /home/fredefox/workspace/GrammaticalFramework/gf-core/.stack-work/install/x86_64-linux/lts-12.4/8.4.3/share/x86_64-linux-ghc-8.4.3/gf-3.9/lib
             /home/fredefox/workspace/GrammaticalFramework/gf-core/.stack-work/install/x86_64-linux/lts-12.4/8.4.3/share/x86_64-linux-ghc-8.4.3/gf-3.9/lib/alltenses
             /home/fredefox/workspace/GrammaticalFramework/gf-core/.stack-work/install/x86_64-linux/lts-12.4/8.4.3/share/x86_64-linux-ghc-8.4.3/gf-3.9/lib/prelude

`SyntaxLat.gf` is listed in `gf-rgl` though, so I don't know what's amiss. Perhaps @heatherleaf knows?

**Comment by fredefox** [comment]
Running `runghc Make.hs install --langs=+Lat` results in:

    Unable to find: 
      src/src/latin/CompatibilityLat.gf

In `gf-rgl`

**Comment by heatherleaf** [comment]
For me it works with just running make.sh without any arguments, then all languages are compiled. 


You have to set the global env var GF_LIB_PATH to somewhere before installing. 

The RGL will then install in $GF_LIB_PATH/alltenses (I think). After compiling and installing the RGL, you should be able to run this from any directory:

    $ gf
    > i alltenses/LangLat.gfo

(Note the gfo suffix)

I might be wrong in some details, but can’t check until tonight.

**Comment by heatherleaf** [comment]
When you have got the RGL to work, you can try to load the Prima grammar. Probably you have to change the first line of the grammar files:

    --# -path=latin-rgl/api:latin-rgl:.

(Or whatever it says) into:

    --# -path=.:alltenses

Or:

    --# -path=.:path-to-gf-rgl/src/abstract:path-to-gf-rgl/arc/latin:(plus probably some more)

(Note, you should only have to change the 1st line of the main files (PrimaLat, PrimaSwe))

**Comment by fredefox** [comment]
Ok, after running `Make.sh` I get


    PrimaRulesLat.gf:14:
      Happened in the renaming of useS
       constant not found: combineSentence
       given ConjunctionLat, ExtraLat, SyntaxLat, CatLat, Conjunction,
             Extra, Syntax, Cat, ConjunctionLat, ExtraLat, SyntaxLat, CatLat,
             ConjunctionLat, ExtraLat, SyntaxLat, CatLat, ConjunctionLat,
             ExtraLat, SyntaxLat, CatLat, ResLat, CommonX, CatLat, PrimaRulesLat
       constant not found: SPreO
       given ConjunctionLat, ExtraLat, SyntaxLat, CatLat, Conjunction,
             Extra, Syntax, Cat, ConjunctionLat, ExtraLat, SyntaxLat, CatLat,
             ConjunctionLat, ExtraLat, SyntaxLat, CatLat, ConjunctionLat,
             ExtraLat, SyntaxLat, CatLat, ResLat, CommonX, CatLat, PrimaRulesLat
       constant not found: PreV
       given ConjunctionLat, ExtraLat, SyntaxLat, CatLat, Conjunction,
             Extra, Syntax, Cat, ConjunctionLat, ExtraLat, SyntaxLat, CatLat,
             ConjunctionLat, ExtraLat, SyntaxLat, CatLat, ConjunctionLat,
             ExtraLat, SyntaxLat, CatLat, ResLat, CommonX, CatLat, PrimaRulesLat

**Comment by heatherleaf** [comment]
Hmm... I can check tonight. Or you can ask a question in the gf mailing list.

**Comment by fredefox** [comment]
Let's continue the discussion of this in #9

**Comment by heatherleaf** [comment]
@fredefox: I just noticed that `CostTree` still only contains one single `TTree`. Since a menu for a given path is a list of `CostTree`s, won't you get two menu items for "hostis Africam vincit"? (one for a tree with `useCNdefsg` and anther for `useCNindefsg`?)

Perhaps this issue is not quite solved yet.

**Comment by fredefox** [comment]
The "ambiguity" should now be introduced here: https://github.com/MUSTE-Project/MULLE/blob/c2d5be7732d9dcd75286c442146de6b7ec12de99/muste/src/Muste/Menu/Internal.hs#L90-L105

I've added a test-case as well. It's failing ATM, but it should just be because I'm not using your patched grammar.

**Comment by fredefox** [comment]
So even with the patched grammar the test-case is failing. Investigating...

**Comment by fredefox** [comment]
c.f.: 0d70234ecc7f0a0c65cda9d6d36388412853bd87

**Comment by fredefox** [comment]
Ok, so the test-case is still failing. Here's why: The menu that is returned *does* contain

    useS (useCl (simpleCl (useCNindefsg (useN hostis_N)) (transV vincere_V2 (usePN Africa_PN))))

However, never at the same path in the menu. The "indefsg" sentence occurs at [0,0,0]. The "defsg" occurs many other places, but not in [0,0,0]. I'm assuming we should *not* consider this a bug. So we should probably find another test-case.

**Comment by fredefox** [comment]
With f43b688524564a7b9ccae1a41c7b5e80344b355e I feel more confident that all parts of the application are up-to-date with the new representation. We should still add a proper test-case however. When that's done I'm ready to merge this on to `develop`.

**Comment by fredefox** [comment]
Github misunderstood me, disregard the above reference.
