### ISSUE TITLE
CLI: print the number of trees in different stages of filtering

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#30]
Sub-issue #26: Printing the number of trees in different stages of filtering.

```
$ muste-cli --grammar=.../Exemplum --lang=ExemplumSwe --printfilter "flickan slår på en dator"

N:o adjunction trees: 117914
N:o pruned trees: 1234
N:o similar trees: 23456
N:o simtrees only keeping cheapest: 23323
...
```

Note: only add "checkpoints" if they are easy to implement. 
E.g., if it's difficult to count the n:o of similar trees before keeping the cheapest, don't include that statistics.

**Comment by heatherleaf** [comment]
This is not the most prioritised option: don't do it if it will take you more than an hour or so to implement.

**Comment by fredefox** [comment]
> This is not the most prioritised option: don't do it if it will take you more than an hour or so to implement.

Close as WONTFIX
