### ISSUE TITLE
Exercise database: change from trees to strings

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#32]
`DbInit.Data` should be possible to simplify.

- It contains some double information. E.g., `DbInit.Data.lessons` contains grammars and exercise counts, but that should be possible to infer from `DbInit.Data.exercises`.

- The exercises are stored as trees which are difficult to create, and anyway not correct since we have moved to sets of trees... 

    E.g., `Protocol.handleLessonInit`, `Protocol.assembleMenus`, etc change the argument between trees, annotated linearisations and other. 

I'm sure there are other fixes that can be done in the DB interface.

**Comment by fredefox** [comment]
> The exercises are stored as trees

This is incorrect:

https://github.com/MUSTE-Project/MULLE/blob/ff56a6c4c5fd44132d5281e4dda8c8403279783b/muste-ajax/src/Database/Types.hs#L72-L77

An exercise consists of annotated source- and target- linearizations.

Marshalling is implemented via the `FromField`/`ToField` instances for `Annotated`:

https://github.com/MUSTE-Project/MULLE/blob/ff56a6c4c5fd44132d5281e4dda8c8403279783b/muste/src/Muste/Sentence/Annotated.hs#L56-L60

That is, we save the binary representation of the Haskell value.

**Comment by heatherleaf** [comment]
Ok, but in DBinit.Data the exercises are stored as GF abstract trees. 

I want to be able to store an exercise like this:

     (“...ref to pgf...”, “ExemplumSwe”, “ExemplumEng”, “flickan sover i huset”, “a girl sleeps in a bed”)

**Comment by heatherleaf** [comment]
Where are `Annotated` used in the code? I don't think it's necessary after all simplifications we did the last weeks. 

The pipeline is currently similar to this (correct me if I'm wrong):

```
orig_sentence :: [Word] = ...starting sentence...
orig_trees :: {TTree} = parse orig_sentence
sim_trees :: {TTree} = { sim | tree <- orig_trees, sim <- similarTrees tree }
-- ^^ orig_trees `disjoint` sim_trees
orig_annotated :: {([Word], [Node])} = { (linTreeToWords tree, linTreeToNodes tree) | tree <- orig_trees }
-- ^^ invariant: linTreeToWords tree == orig_sentence
sim_annotated :: {([Word], [Node])} = { (linTreeToWords tree, linTreeToNodes tree) | tree <- sim_trees }
-- ^^ orig_annotated `disjoint` sim_annotated
menu :: Map Selection {[Word]} = mapsetFromSet { (getSelection orig_nodes sim_nodes, sim_lin) | (_, orig_nodes) <- orig_annotated, (sim_lin, sim_nodes) <- sim_annotated }

where mapsetFromSet :: {(key, value)} -> Map key {value}
      parse :: [Word] -> {TTree}
      linTreeToWords :: TTree -> [Word]
      linTreeToNodes :: TTree -> [Node]
      getSelection :: [Node] -> [Node] -> Selection
```

Caveat: I wrote this from top of my head, could be lots of errors. I dismiss optimisations here, but I hope I'm conceptually correct. 

**Anyway**, the downside is that the input to the pipeline is an unannotated sentence (`[Word]`), and the output is too.

**Comment by fredefox** [comment]
Annotated sentences are used in many places in the code base:

```
git grep -E '\bAnnotated\b' | wc --lines
115
```

For one thing it's used in `ServerTree`.

**Comment by fredefox** [comment]
The annotations are for instance used to highlight the words in the UI. A hash is calculated from the annotation and an rgba-value is generated from this.

**Comment by heatherleaf** [comment]
That's true! So the output from the pipeline is Annotated. But the input doesn't have to be. Because we anyway have to parse it to get all possible Annotated strings from that sentence.

**Comment by fredefox** [comment]
> Doing this will require more work because an exercise only consists of a single (annotated!) linearization.

Is this the path that we should go? This will require changing the definition of what constitutes an exercise.

**Comment by heatherleaf** [comment]
Yes I think so. 

If we see it from the user's perspective, an exercise only involves (unannotated) sentences. So, the user cannot see the difference between these two Annotated:

1. `[("flickan", girl), ("slår", hit), ("på", on), ("datorn", computer)]`
2. `[("flickan", girl), ("slår", turnon), ("på", turnon), ("datorn", computer)]`

So, we should never have (1) without (2), or the other way round

**Comment by fredefox** [comment]
I think this is fair. I was just concerned because I didn't feel that cleaning up the code to dimplify the db init script warranted such a big change.

**Comment by fredefox** [comment]
I've solved pt. 1 of this issue with the simplest possible change. It would probably be more correct to not even have a row for the amount of exercises in a lesson. The DBMS should already be able to answer such questions.

**Comment by fredefox** [comment]
Closing in favor of #37.
