### ISSUE TITLE
Change styling

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#35]
I've changed styling a bit mainly based on my own taste. It's in the branch `stylish`. Could you tell me what you think?

**Comment by heatherleaf** [comment]
thanks,
mostly an improvement, but I did some minor changes

**Comment by fredefox** [comment]
I think you've forgotten to push your changes.

Do you like it enough that I can merge it in? Styling is so super subjective...

**Comment by heatherleaf** [comment]
No, I pushed: e76c28b476ff7f573b6f4865c5dd5541a627499b

**Comment by heatherleaf** [comment]
Yes, you can merge. And there will probably be more style changes over time - it's very subjective

**Comment by fredefox** [comment]
I forgot to pull xD

**Comment by fredefox** [comment]
Looks a bit weird with the rounded corners when it's just an underline IMO...

**Comment by fredefox** [comment]
Merged in df0edcb2d0c118a20002bfcc1f8de02db23bbf32

**Comment by heatherleaf** [comment]
I thought it was a nice side-effect :)
