### ISSUE TITLE
Missing menu items

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#36]
After the recent updates, I noticed that the menus are too sparse now. Here are some missing menu items that should be there.

### Examples for "flickan slår på en dator"

This is still a problem (mine to think about). This menu is never shown because `{}` is an empty selection:
```
{}: flickan slår på en dator
flickor slår på en dator
flickorna slår på en dator
```

The menu for `{0-0}` should also insert adjectives:
```
{0-0}: [ ] flickan slår på en dator
[ den blåa ] flickan slår på en dator
[ den dåliga ] flickan slår på en dator
...
```

There should be a menu for `{1-1}`:
```
{1-1}: flickan [ ] slår på en dator
flickan [ Johan ] slår på en dator
flickan [ idag ] slår på en dator
flickan [ i boken ] slår på en dator
...
```

And for `{2-2}`:
```
{2-2}: flickan slår [ ] på en dator
flickan slår [ idag ] på en dator
...
```

And for `{4-4}`:
```
{4-4}: flickan slår på en [ ] dator
flickan slår på en [ blå ] dator
flickan slår på en [ dålig ] dator
...
```

And for `{5-5}`:
```
{5-5}: flickan slår på en dator [ ]
flickan slår på en dator [ Johan ]
flickan slår på en dator [ idag ]
flickan slår på en dator [ i boken ]
...
```

And for this:
```
{0-1,2-2}: [ flickan ] slår [ ] på en dator
[ idag ] slår [ flickan ] på en dator
[ nu ] slår [ flickan ] på en dator
```

**Comment by fredefox** [comment]
Can you tell me which version you used that showed the desired behavior?

**Comment by fredefox** [comment]
Bisecting...

`[ den blåa ] flickan slår på en dator` not in `0.2.5.0`

**Comment by fredefox** [comment]
Indeed there is a big difference in the menus:

[muste-0.2.4.0.txt](https://github.com/MUSTE-Project/MULLE/files/2410302/muste-0.2.4.0.txt)
[muste-0.2.5.0.txt](https://github.com/MUSTE-Project/MULLE/files/2410303/muste-0.2.5.0.txt)

**Comment by fredefox** [comment]
I'm done bisecting. The procedure I used was to run the CLI with the sample input and simply check that the amount of suggestions returned is the same as in `0.2.4.0` (i.e. 222 suggestions). Doing this reveals that:

```
8d2d65741a767e45535c83fc288a4c822e2fd821 is the first bad commit
commit 8d2d65741a767e45535c83fc288a4c822e2fd821
Author: Peter Ljunglöf <peter.ljunglof@heatherleaf.se>
Date:   Wed Sep 12 09:02:51 2018 +0200

    filtering the tree substitutions

:040000 040000 06be3dcdc7a182fd03cb2da9254da4ef815e042b 8fcaa0799aa9edc8d416b8af487df7f2262457ed M	muste
```

The number of suggestions per commit is:

```
   222 muste-0.2.4.0.txt
    77 muste-0.2.5.0.txt
   222 muste-2b6d149.txt
   222 muste-525d01a.txt
    75 muste-61d7b75.txt
   112 muste-7fcd17b.txt
   112 muste-8d2d657.txt
   112 muste-daabe66.txt
```

As you can see the number is dancing a bit back and forth, this is perhaps a bit worrying.

**Comment by fredefox** [comment]
And with the above commit:

    196 muste-a6082b9.txt

Notice that there is still 26 suggestions fewer than in `0.2.4.0`. Let me know if you want me to investigate this further. Otherwise I'll close it for now.

**Comment by heatherleaf** [comment]
Sorry, now we're back with too many menu items again. 

I think the version closest to what I'm looking for is the one with 112 suggestions. Of the ones you list above, 7fcd17b is the most recent, and then after 10 more commits, 61d7b75 goes down to 75 suggestions. So somewhere between those two, the number of suggestions dropped too much.

**Comment by heatherleaf** [comment]
More regression tests: 
The problem was introduced in 61d7b75, because its parent (11129bb) has 112 suggestions.

61d7b75 was whe we changed the type of AdjunctionTrees to:

    newtype AdjunctionTrees 
        = AdjunctionTrees (M.Map (Category, MultiSet Category) [TTree])

which improved speed a lot. But apparently we introduced a bug too, let's hope it wasn't the bug that improved the speed.

**Comment by fredefox** [comment]
Yeah I was suspecting this might be the culprit. Either it was not a valid program transformation or perhaps there's a problem with the Ord instance for multisetb although that seems unlikely

**Comment by fredefox** [comment]
I'm not quite sure how to fix this without reverting the type of `AdjunctionTrees`. I'm suspecting this is the cause of it. Doing that will of course hurt performance.

**Comment by fredefox** [comment]
NB: You can compile the CLI with -DDIAGNOSTICS to see the adjunction trees.

**Comment by fredefox** [comment]
That change was introduced in 1772b7d7, so is unfortunately not available before that point in time.

**Comment by heatherleaf** [comment]
I will look into this, but have to write three reviews first :/

**Comment by fredefox** [comment]
uh-oh! Sounds like you have to do a lot of reading. A correction: -DDIAGNOSTICS doesn't give you the whole object, only the keys and how many trees are at that key. Here's a command line to get you started:

    stack install --force-dirty muste --ghc-options="-DDIAGNOSTICS"

**Comment by heatherleaf** [comment]
Found the bug! It was introduced in 61d7b75, in `Prune.hs`. This diff makes it work for that commit:

```diff
similarTreesForSubtree :: TTree → AdjunctionTrees → [SimTree]
-similarTreesForSubtree tree adjTrees = similiarTrees trees tree
+similarTreesForSubtree tree adjTrees = similiarTrees cat adjTrees tree
   where
-    trees ∷ [TTree]
-    trees = fromMaybe errNoCat $ do
-      Mono.lookup (cat, metas) adjTrees
     cat = case tree of
       (TNode _ (Fun c _) _) → c
       _ → errNotNode
-    metas = Grammar.getMetas tree
-    errNoCat = error
-      $  "Muste.Prune.similarTreesForSubtree: "
-      <> "The tree with the given category and/or metas does not exist."
     errNotNode = error
       $  "Muste.Prune.similarTreesForSubtree: "
       <> "Non-exhaustive pattern match"
 
 -- O(n^3) !!!! I don't think this can be avoided though since the
 -- output is bounded by Ω(n^3).
-similiarTrees ∷ [TTree] → TTree → [SimTree]
-similiarTrees adjTreesForCat tree = do
+similiarTrees ∷ Category → AdjunctionTrees → TTree → [SimTree]
+similiarTrees cat adjTrees tree = do
   (pruned, branches) ← pruneTree tree
+  let metas = Grammar.getMetas pruned
+  adjTreesForCat     ← maybeToList $ Mono.lookup (cat, metas) adjTrees
   pruned'            ← filterTrees adjTreesForCat pruned
   tree'              ← insertBranches branches pruned'
   pure (tree `treeDiff` tree', tree', pruned, pruned')
 
+maybeToList :: Maybe a -> [a]
+maybeToList (Just a) = [a]
+maybeToList _ = []
```

I'll try to update the currect head, but I'm not sure I will do it very well...

The problem was that you looked up in `adjTrees` too early. In `similarTreesForSubtree`, the `metas` will always be `[]` because the `tree` is pruned (it has no holes yet). So the lookup has to move to `similarTrees`, when the `tree` has been `pruned`.

**Comment by fredefox** [comment]
That's great! Very good catch! I'll have a look at it tomorrow though. I'm totally done for today.

**Comment by fredefox** [comment]
I'm assuming the diff is to be applied on top of the commit you cite. Protip: If you copy the first few lines from `git diff` as well the patch can be applied with `git apply`.

**Comment by heatherleaf** [comment]
Cool, didn't know about `git apply`, so I did it the hard way instead :)

**Comment by heatherleaf** [comment]
Remaining missing items... (copied and filtered from first comment above) All these are for me to think about.

This menu is never shown because {} is an empty selection:
```
{}: flickan slår på en dator
flickor slår på en dator
flickorna slår på en dator
```

Missing items for {1-1}:
```
{1-1}: flickan [ ] slår på en dator
flickan [ i boken ] slår på en dator
flickan [ på huset ] slår på en dator
...
```

And for {5-5}:
```
{5-5}: flickan slår på en dator [ ]
flickan slår på en dator [ i boken ]
flickan slår på en dator [ på huset ]
...
```

**Comment by fredefox** [comment]
@heatherleaf, you're assigned to this. Should I take it that you're still taking charge?

**Comment by heatherleaf** [comment]
> @heatherleaf, you're assigned to this. Should I take it that you're still taking charge?

yes, still thinking... empty selections is tackled in issue #43

**Comment by heatherleaf** [comment]
Remaining missing menu items

### inserting PPs (Adv)

For {1-1}:
```
{1-1}: flickan [] slår på en dator
flickan [i boken] slår på en dator
flickan [på huset] slår på en dator
...
```

For {5-5}:
```
{5-5}: flickan slår på en dator []
flickan slår på en dator [i boken]
flickan slår på en dator [på huset]
...
```

### removing PPs (Adv)

For {2-3}:
```
{2-3}: flickan slår [på] en dator
flickan slår [] en dator
```

### inserting Conjs

For {0-0}:
```
{0-0}: [] flickan slår på en dator
[pojken och] flickan slår på en dator
```

For {1-1}:
```
{1-1}: flickan [] slår på en dator
flickan [och pojken] slår på en dator
```

### Removing Conjs

These are for the sentence "flickan och pojken slår på en dator

For {0-2}:
```
{0-2}: [flickan och] pojken slår på en dator
[] pojken slår på en dator
```

For {1-3}:
```
{1-3}: flickan [och pojken] slår på en dator
flickan [] slår på en dator
```

**Comment by heatherleaf** [comment]
done

**Comment by heatherleaf** [comment]
now works, but speed could be improved
