### ISSUE TITLE
Store *un*annotated sentences in exercises

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#37]
Replaces #32.

**Comment by heatherleaf** [comment]
Both storing as a tree and as a string (or list of words) has potential problems:

Storing as a tree:
- pros: language-independent; the generated sentence is always correct
- cons: difficult to write trees by hand; difficult to read trees; sensitive to changes in the grammar

Storing as a string:
- pros: easy to write exercises by hand; easy to understand the exercises when looking at the code; insensitive to changes in the grammar api
- cons: depends on the language; sensitive to parsing errors

No absolute clear winner here, but I prefer to be able to write/read what's stored in the DB.

**Comment by fredefox** [comment]
I'm closing this with [0.2.5.2](https://github.com/MUSTE-Project/MULLE/releases/tag/0.2.5.2).
