### ISSUE TITLE
GUI: look nice for different phones and tablets

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#39]
The GUI should look nice and be useful for both phones and tablets. Things to think about:

- margins, button sizes
- size of words and menu items (should be selectable by a finger)
- how to select between two words (currently the space grow on mouseover, but a touch-screen doesn't have mouseover)

**Comment by fredefox** [comment]
I removed the expansion of the selectable space on mouse-over because I thought it didn't look so nice.

**Comment by heatherleaf** [comment]
> Maybe just make the spaces a teency bit wider?

Perhaps that's enough.

One thing I've thought about but don't know if it's possible: To extend the "sensitive area" of a space so that it goes into the outer edges of a word. Like this:

    +-----+---------+-----+---+-----+-------+-----+
    |    f|l i c k a|n   s|l å|r   p|o j k e|n    |
    +-----+---------+-----+---+-----+-------+-----+

**Comment by heatherleaf** [comment]
Note that the letters should not be highlighted if you select a space, even though they are in the sensitive area. I.e., if you select the first space, the "f" should not be highlighted. But the "f" and "n" should be highlighted if you select "licka"

**Comment by fredefox** [comment]
I just thought about my idea about making the spaces wider, it's true the small clickable spaces are certainly suboptimal for hand-held devices. As previously stated the mouse-over event doesn't help us here. What most modern mobile browser do, however, is show an extra popup when you click on a clickable space that is very close to another one. So that should help alleviate the "fat finger" syndrome.

**Comment by fredefox** [comment]
Perhaps this could be used for increasing the clickable area:

https://stackoverflow.com/a/20327676/1021134

 It feels pretty hacky though.

**Comment by heatherleaf** [comment]
> Perhaps this could be used for increasing the clickable area:

Looks like a nice and easy idea, and not very hacky to me.

**Comment by fredefox** [comment]
I've increased the spacing in 0eddf93020f60f33fd6c407b33c25a0a3c56aec3 let's revisit the idea I quoted from SO if this doesn't work so nicely on phones. I'm having a weird issue with my phone caching the site, so I can't test it on my phone right now.

**Comment by fredefox** [comment]
Remaining issues:

- [ ] There is an issue with the exercise and lesson list not being vertically centered correctly in firefox.

**Comment by fredefox** [comment]
This should be fixed in 2ee4b32b81e4640ca954a464bd67b6c0c3c67976 do you feel I missed something in this issue, then please reopen.
