### ISSUE TITLE
Make a lesson grammar accept errors

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#4]
Support for automatically generating 'wide' grammars from 'narrow' ones.

The interface must also be extended to add support for "fixing
mistakes".

**Comment by heatherleaf** [comment]
This requires to know how the GF compiler is implemented (at least some of it), because it involves automatically modifying a grammar.

**Comment by heatherleaf** [comment]
Here's an attempt to a description of the kind of transformation I want: 

https://github.com/MUSTE-Project/MULLE/wiki/Transforming-a-GF-grammar

**Comment by fredefox** [comment]
Cool. I'll have a look.

**Comment by heatherleaf** [comment]
When you're at it, please have a look at the [GF crash course](https://github.com/MUSTE-Project/MULLE/wiki/GF-crash-course), and give comments.

**Comment by heatherleaf** [comment]
this is being done as part of the GF core: https://github.com/GrammaticalFramework/gf-core/issues/29

**Comment by heatherleaf** [comment]
See here: https://github.com/MUSTE-Project/gf-canonical-transforms

**Comment by heatherleaf** [comment]
Seems to work quite nice now
