### ISSUE TITLE
Limiting pruning / adjunction trees: depth vs size

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#46]
Add extra options and code for limiting pruning and adjunction trees: 

    --max-prune-depth
    --max-prune-size
    --max-adjtree-depth
    --max-adjtree-size

Note that I changed the names: 
- "max" instead of "limit": I have a hunch that "max" is more common than "limit", but I can be convinced otherwise
- "adjtree" instead of "search": because "search" is a too general term

Whatever names we choose, I think that the variable names should be the same as above (camlCase -- i.e. `maxPruneDepth` etc), here:

https://github.com/MUSTE-Project/MULLE/blob/8c20a585f2a9d9764bc9260240dd04cf8318263a/muste/app/Options.hs#L19-L29

**Comment by fredefox** [comment]
I have no strong feelings about the variable names.

**Comment by heatherleaf** [comment]
Ok, then let's go for my suggestion above

**Comment by fredefox** [comment]
I'll look into this now.

**Comment by fredefox** [comment]
Now that I've dug a bit deeper I've discovered a potential issue with the size limiter. From what I can tell de do a depth-first search, so if we limit the size naively we'll get skewed results. If we want to change this we need to change the algorithm to do breadth first. This requires more work.

**Comment by fredefox** [comment]
In the above commit I've added the options to the CLI with the names you wanted, they are currently unused, however. See my previous comment.

**Comment by fredefox** [comment]
So my question is. Do we want to invest the time in changing the search algo to do breadth-first?

**Comment by heatherleaf** [comment]
It is possible to do it depth-first, see c325d7c278f31d243866d25cafb1f806d5749107 and 6e450bb16fc84ff21e793ed17058f7443784d6fb

(I had to remove all your nice code using a `Builder`, because I don't understand how to use it... sorry for that :)
