### ISSUE TITLE
GUI: support for other scripts 

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#48]
GF can handle Unicode, so this should work. But we have to test, so we need toy grammars in e.g.:

- Cyrillic 
- Chinese / Japanese
- Arabic

**Comment by fredefox** [comment]
I don't think this is unsupported.

**Comment by heatherleaf** [comment]
Tested with the ExemplumChi grammar, and it works like a charm.

Perhaps it would be nice to be able to decrease the inter-word space for some languages (read Chinese). This is because Chinese doesn't have spaces at all, so this seems to be too large spacing:

![image](https://user-images.githubusercontent.com/1324196/46307967-ad7b6680-c5b8-11e8-82c7-6c8adfd33c37.png)

**Comment by heatherleaf** [comment]
Any idea on how to make language-dependent inter-word spacing?

**Comment by fredefox** [comment]
My idea would be to add a config-object to the response from the `lesson` handler.

**Comment by heatherleaf** [comment]
unicode works out of the box, so closing this
