### ISSUE TITLE
Prune suggestions that can be reached in multiple steps

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#5]
The idea is to not show suggestions that can be reached by doing
multiple replacements.  Imagine the trees form a graph like so:

       a
     ↙
    b  ↓
     ↘
       c

Where the nodes are individual trees and the edges mean that we can
reach one from the other.  If the path `a → b → c` is cheaper than `a
→ c`, then we want to exclude that path (`a → c`) from the suggestions
displayed at `a`.

Note that the amount of trees we can reach from one state is huge.
For this reason I propose defining a function `closeEnough ∷ TTree →
Set TTree`. `closeEnough t` returns a set of states that want to
consider when suggestion replacements for `t`.

Algorithm:

    1. Fix a start node A
    2. For each X ∈ closeEnough(A), remember cost(A,X)
    3. For each X ∈ adjacent(A)
       if edge(A, X) <= cost(A, X)
       then include X
       else eclude X

Step 2 is really just some variant of a shortest path algorithm with a
cut-off.

**Comment by fredefox** [comment]
@heatherleaf @daherb To implement this it would be nice to have an example where this situation arises. I haven't been able to find such an example from the exercises that I have installed locally. I found an old `.sql` file with some exercises coded into it that I scraped out and put back the database[^1].

If you can lend me any assistance in creating an exercise where this happens or maybe just some data for the internal representation (e.g. 3 `TTree`'s as in the example above) that would be great.

[^1]: The was exercises are serialized has changed

**Comment by heatherleaf** [comment]
Here's an example from the online demo: https://cse-principia.cse.chalmers.se/muste/muste.html

The first lesson, and first exercise is "kejsaren Augustus erövrar Afrika". If you click a couple of times so that "erövrar Afrika" is selected, then you get a huge list of suggestions, such as "har fienden", "blir flickan", etc. Those shouldn't be suggested, since "erövrar -> har" and "Afrika -> fienden" are two smaller steps that lead to the same result.

**Comment by fredefox** [comment]
Do you know which version is running in the online demo? I don't think I have that exact exercise installed locally, but I'm *guessing* that a similar situation should occur for a sentence such as

      Augustus [är kejsaret]

But the suggestions I get in this case are:

```
Augustus är romersk
Augustus är orolig
Augustus är god
Augustus är uttländsk
Augustus är lycklig
Augustus är enorm
Augustus är glad
Augustus är stor
Augustus är vis
Augustus är besegrad
Augustus säger
```

Which seems reasonable to me. I think this is the typical situation that highlights the need to be sure that we are talking about the same version.

**Comment by fredefox** [comment]
If it's possible for me to upload versions to `somewhere.chalmers.se` do let me know. Perhaps @daherb can chime in on this.

**Comment by heatherleaf** [comment]
Perhaps my example is covered by the changes I did to Prune.collectSimilarTrees - version 1c filters out all examples where the adjunction trees have something in common. 

The following would be an example which I don’t think is covered by collectSimilarTrees:

usePN Africa_PN  —>
useCNdefsg (attribCN (useA victus_A) (useN imperium_N))

This should be filtered out, because of:

usePN Africa_PN  —>
useCNdefsg (useN imperium_N)  —>
useCNdefsg (attribCN (useA victus_A) (useN imperium_N))

**Comment by fredefox** [comment]
After having looked at this for a bit and thought really hard about it, I think this issue has already been addressed. I've factored out a function `onlyKeepCheapest` which (given some of the invariants at the time it is called) seem to achieve exactly this. See e.g. the comment accompanying it introduced in dc29b2a68ad2c8e9e682a26b08e4738a10e84f26. [Permalink to that comment](https://github.com/MUSTE-Project/MULLE/blob/dc29b2a68ad2c8e9e682a26b08e4738a10e84f26/muste/src/Muste/Prune.hs#L88).

The specific functionality seem to have been introduced in

```
commit ba053b03fbfcbc0607622314846c215c437316b6
Author: Peter Ljunglöf <peter.ljunglof@heatherleaf.se>
Date:   Mon Mar 5 12:58:39 2018 +0100

    Improved pruning
```

So if the demo running on the web is older than this, then I suspect you have already fixed it :1st_place_medal:.

I'll see if I can create a test case covering the example you've mentioned above and see where that brings me.

**Comment by fredefox** [comment]
Oh, and I wanted to add that I pushed some functionality into `Muste.Prune` so we reduce the coupling between that module and `Muste`. `Prune` no longer exports `collectSimilarTrees` but rather a function:

`replaceTrees :: Grammar -> AdjunctionTrees -> TTree -> Map Path [(Int, TTree)]`

That collects all the similar trees *and* performs the substitutions. Here is the haddock header for it:

```
-- | @'replaceTrees' grammar adjTs tree@ finds all trees similar to
-- @tree@ in @adjTrees@.  Return a mapping from 'Path''s to the tree
-- you get when you replace one of the valid trees into that given
-- position along with the "cost" of doing so.
```

**Comment by heatherleaf** [comment]
Oh, perhaps I did that... but it seems to be a quite slow solution (quadratic, right?)
Hopefully `onlyKeepCheapest` can be optimised (if necessary).

Seems good with `replaceTrees` and the new AdjunctionTrees module, and reducing coupling with Muste.

**Comment by fredefox** [comment]
Ok, managed to test this. At least for the `Prima.pgf` that I have it is *not* the case that

    useCNdefsg (attribCN (useA victus_A) (useN imperium_N))

is included as a suggestion for

    usePN Africa_PN

As returned by `replaceTrees`.

**Comment by fredefox** [comment]
I'll close this for now until. Once you've tried running this version, if you see the problem is still there, just reopen this.

**Comment by daherb** [comment]
@fredefox I can give you access to my server cse-principia.cse.chalmers.se. Just mail me a ssh-key an I  will create an account for you. Then, if you have the application listening on localhost:8081 it can be accessed via https://cse-principia.cse.chalmers.se/mulle-dev/
