### ISSUE TITLE
DB/GUI: User registration from the GUI

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#50]
It would be useful if users could self-register from the login page.

I guess we need to have some Terms of Agreement, etc.

I have no idea how difficult this is to implement.

**Comment by fredefox** [comment]
I'll look at this now.

**Comment by heatherleaf** [comment]
Seems to work fine (except the things you already know: not showing if the user already exists, and no feedback when the user is created)

**Comment by fredefox** [comment]
Closing this for now. Let's create separate issues for polishing this. We have a bare-bones implementation now. The way that feedback is given to the user that a user is created is simply by showing the log-in page.
