### ISSUE TITLE
GUI: Wrong menu placement

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#51]
When clicking between words (for insertion), the menu is too high up. This makes it impossible to click the space again. 

Note, this is the case for Chrome and FIrefox:
![image](https://user-images.githubusercontent.com/1324196/46291388-9aec3780-c58e-11e8-81ef-eda25756bcbc.png)

It looks fine in Safari:
![image](https://user-images.githubusercontent.com/1324196/46291444-c53df500-c58e-11e8-9482-c5c4e53d6805.png)

**Comment by fredefox** [comment]
Yes is likely a regression from when I introduced an "overlay" to better handle when the user want to get out of the menu. You'll notice that the background get's a bit darker now when you open a menu. I took the creative liberty of adding that in as well. Just let me know if you don't like it.

**Comment by heatherleaf** [comment]
> You'll notice that the background get's a bit darker now when you open a menu. I took the creative liberty of adding that in as well. Just let me know if you don't like it.

Looks fine

**Comment by fredefox** [comment]
The issue is only related to the empty spaces and it was introduced in 0357f9a39adb640cf6c12c5c5226e001ec2da884

**Comment by fredefox** [comment]
It's perhaps not so surprising, but nonetheless rather unfortunate, that upgrading jQuery introduces regressions. After all, we upgraded from jQuery 1.11.1 (May 1 2014) to jQuery 3.3.1 (most recent).

**Comment by fredefox** [comment]
This should be fixed in 3118ee3c2eb74cc7183cd946771e078d6b3fd905
