### ISSUE TITLE
GUI: menu not disappearing

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#52]
The menu doesn't disappear when a menu item is selected:

![image](https://user-images.githubusercontent.com/1324196/46292654-b9076700-c591-11e8-89c8-8a1272e1aef6.png)

The screenshot is when I have selected "a bad king..." from the menu, and the sentence is updated, but the menu doesn't disappear until I click somewhere.

**Comment by fredefox** [comment]
Oh yeah. I was actually aware of this. I'll fix it.

**Comment by fredefox** [comment]
Closed in 9e3ac6c961a5d1c3c3d93dfd5e8b16ee5c6e017d
