### ISSUE TITLE
GUI: disappearing menus

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#53]
The subsequent menus have disappeared from the GUI. I.e., when I have a menu open and click on the same work again to get the next menu, it instead just deselects everything.

### Examples from Exemplum

The following menu cannot open anymore, because it would need to either click "many" twice or "kings" twice:
```
{0-2,1-2}: [ many [ kings ] ] love Paris
[ John [ ] ] loves Paris
[ Paris [ ] ] loves Paris
[ he [ ] ] loves Paris
[ it [ ] ] loves Paris
[ she [ ] ] loves Paris
[ they [ ] ] love Paris
```

The same for the following Swedish menu:
```
{4-6}: en god kung läser [ en bok ]
en god kung läser [ Johan ]
en god kung läser [ Paris ]
en god kung läser [ dem ]
en god kung läser [ det ]
en god kung läser [ henne ]
en god kung läser [ honom ]
```

**Comment by heatherleaf** [comment]
Possibly it happened when you introduced the "greying out" of everything except the menu. But that's just a guess, could be anything. I haven't tested old commits to see when the bug was introduced.

**Comment by fredefox** [comment]
That's exactly right. The overlay is there to catch click events outside the menu, but we want to still be able to cycle the menus. I should be able to fix this by modifying the z-index of the `.clickable` that introduced the menu.

**Comment by fredefox** [comment]
67e616933843c941930ffa0bd7a11fa39cb69966 closes this
