### ISSUE TITLE
Use front end framework

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#6]
This will require molding the existing hand tailored JavaScript to
work with a framework.  Luckily most browser based frameworks are
designed to interop with old school JavaScript so perhaps we can reuse
most parts, but there certainly are parts of the existing
implementation that would benefit greatly from being controlled in a
more structured/framework-y way.  The obvious down side of going ahead
with this is that it will require time and increases the risk of
regressions.  Whether or not it is work it must in the end be a
decision for @heatherleaf to make.

Here is my list of suggestions for a framework to use:

* purescript
* elm
* angular

Pros/Cons:

PureScript: Very similar to Haskell.  I played around with it the
other day, but it's not obvious to me how stable/mature this is.  It
has a front-end framework called Halogen.

Elm: Also very similar to Haskell.  Probably similar considerations to
the above.

Angular: Very mature.  May be more difficult for people in the future
to maintain unless they have some experience with it &emph; I have
some experience with it.

**Comment by heatherleaf** [comment]
I don’t know much about different JS frameworks. But since the current frontend code is not the largest one, I would prefer a light-weight framework. Perhaps more of

**Comment by fredefox** [comment]
> Do you think it’s difficult to convert to Elm or Purescript?

They should both have good interop support for JavaScript, so it should be possible to copy and paste some of the code. But the way that the code interacts with the DOM I suspect needs to be more or less rewritten. Converting it is gonna be a bit of an exploratory mission for me TBH, but definitely fun! :D

**Comment by fredefox** [comment]
Removing milestone since this is on hold.

**Comment by heatherleaf** [comment]
will not fix this, at least not in the foreseeable future
