### ISSUE TITLE
GUI: missing menus

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#62]
There are sometimes many fewer menus in the GUI than on the CLI:

```
$ muste cli -G novo_modo/Prima -L PrimaSwe --print-compact "han är vis"

Selection                                                    N:o menu items
{}: han är vis                                               1
{0-1}: [ han ] är vis                                        29
{0-1,1-1}: [ han [ ] ] är vis                                13
{0-1,2-2}: [ han ] är [ ] vis                                1
{2-3}: han är [ vis ]                                        9
{1-3}: han [ är vis ]                                        21
```

But in the GUI:
```
>> console.log(JSON.stringify(DATA.trg.sentence.linearization))
[{"concrete":"han","classes":["he_PP"],"matching-classes":{}},{"concrete":"är","classes":["copula_VA"],"matching-classes":{}},{"concrete":"vis","classes":["sapiens_A"],"matching-classes":{}}] 

>> console.log(JSON.stringify(DATA.trg.menu))
[[[],[
    [[],[{"concrete":"han","classes":["he_PP"]},{"concrete":"är","classes":["copula_VA"]},{"concrete":"vis","classes":["sapiens_A"]}]]]],
[[[2,3]],[
    [[[2,3]],[{"concrete":"han","classes":["he_PP"]},{"concrete":"är","classes":["copula_VA"]},{"concrete":"besegrad","classes":["victus_A"]}]],
    [[[2,3]],[{"concrete":"han","classes":["he_PP"]},{"concrete":"är","classes":["copula_VA"]},{"concrete":"enorm","classes":["ingens_A"]}]],
    (...)
]]
```
So, the GUI is missing the menus {0-1}, {0-1,1-1}, {0-1,2-2}, {1-3}. I guess it's not a problem in the GUI but somewhere in the Ajax server, because the client only receives a menu with 2 items:

![image](https://user-images.githubusercontent.com/1324196/46392741-b23c3980-c6e2-11e8-8fef-9db2a7da9ce9.png)

**Comment by heatherleaf** [comment]
Strangely enough I don't see that problem with the Exemplum grammars, only with Prima and Secunda.

1st to try: can you reproduce my problem?

**Comment by fredefox** [comment]
I get the same in the web gui as you do in the CLI.

**Comment by heatherleaf** [comment]
Very strange. Can you try again with the updated Prima grammar I push just now?

**Comment by heatherleaf** [comment]
This is how it looks like in Chrome after I selected the Prima lesson:

![image](https://user-images.githubusercontent.com/1324196/46399116-2da7e600-c6f7-11e8-8009-883d7715ce55.png)

As you can see in the Network pane, `src.menu` only has 4 elements, and `trg.menu` only 2.

**Comment by fredefox** [comment]
Yes I see this now.

**Comment by fredefox** [comment]
Could this be related to the search-parameters? I don't know if you enabled them.

**Comment by fredefox** [comment]
It looks like those options are still not used. Note the use of `mempty` here:

https://github.com/MUSTE-Project/MULLE/blob/4e72ba49bc5be0f3bece195cef9cfdda51785e75/muste-ajax/src/Protocol.hs#L546

**Comment by fredefox** [comment]
Aha!

You'll notice that in `Protocol` we do:

https://github.com/MUSTE-Project/MULLE/blob/4e72ba49bc5be0f3bece195cef9cfdda51785e75/muste-ajax/src/Protocol.hs#L546

Whereas in `Muste.Repl` we do:

https://github.com/MUSTE-Project/MULLE/blob/4e72ba49bc5be0f3bece195cef9cfdda51785e75/muste/app/Muste/Repl.hs#L211

**Comment by heatherleaf** [comment]
dooh, it is the depth-search parameter; my mistake

thanks, you can move on, nothing to see here

**Comment by heatherleaf** [comment]
when I set `novomodoDepthLimit` to Nothing, I get all menus
