### ISSUE TITLE
New lesson setting: turn on/off highlighting

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#74]
To make a lesson more difficult we could turn of the automatic highlighting between words. I can do that by commenting out line 606 in `app.js`: 
https://github.com/MUSTE-Project/MULLE/blob/d40af8099485267e1f4caa67d7a7012c144fa652/muste-ajax/static/js/app.js#L605-L607

I would like a setting in `lessons.yaml`, e.g. "highlight-matches" which can be true or false

**Comment by fredefox** [comment]
What should the default be?

**Comment by heatherleaf** [comment]
on I think, since that's what we use now

**Comment by fredefox** [comment]
Closed in 9f94301
