### ISSUE TITLE
Truncate menu items

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#75]
When we have long sentences, the menu items become very long, even when there is only 1-2 words that change. E.g.:
```
{10-11}: many good kings in Paris don't love a big blue [book] in a house
many good kings in Paris don't love a big blue [boy] in a house
many good kings in Paris don't love a big blue [computer] in a house
many good kings in Paris don't love a big blue [father] in a house
many good kings in Paris don't love a big blue [friend] in a house
many good kings in Paris don't love a big blue [girl] in a house
many good kings in Paris don't love a big blue [house] in a house
many good kings in Paris don't love a big blue [king] in a house
many good kings in Paris don't love a big blue [mother] in a house
```

It would be nice if the menu (in the GUI) could be truncated to only show 1-2 words of context around the selected words, something like this:
```
{10-11}: many good kings in Paris don't love a big blue [book] in a house
...blue [boy] in...
...blue [computer] in...
...blue [father] in...
...blue [friend] in...
...blue [girl] in...
...blue [house] in...
...blue [king] in...
...blue [mother] in...
```

If the menu item consists of several selections, then the simple solution is to only truncate the outer ends:
```
{0-0,5-6}: [] many good kings in Paris [don't] love a big blue book in a house
[something in] many good kings in Paris [doesn't] love...
[something on] many good kings in Paris [doesn't] love...
[something to] many good kings in Paris [doesn't] love...
```

Alternatively we could truncate between the selections too:
```
{0-0,5-6}: [] many good kings in Paris [don't] love a big blue book in a house
[something in] many ... Paris [doesn't] love...
[something on] many ... Paris [doesn't] love...
[something to] many ... Paris [doesn't] love...
```
but I'm not sure if this is better

**Comment by fredefox** [comment]
I have a WIP preview of this in 657eed1. I mark words within a range of the selected words as being relevant. Currently I just grey out the irrelevant words even more.

TODO:

- [ ] Fold consecutive irrelevant words under an ellipsis.

**Comment by fredefox** [comment]
This is now done in 6565bcc. Note that the "threshold" is set to 1 word! I just used this low value for testing purposes. Just let me know what you want it to be.

One issue we haven't thought about: It's not possible to re-show the context. Perhaps this is not even a desired feature?

**Comment by fredefox** [comment]
Oh! And another issue. If the edit is a deletion, then the all words are marked as being irrelevant. This is because relevancy is defined as proximity to a "selected" word. And since there are not selected words...

**Comment by fredefox** [comment]
> can the n:o of words in the context be a lesson-specific setting? it could e.g. depend on the language

Everything is possible! :)

**Comment by heatherleaf** [comment]
if the edit is a deletion, there are two possibilities:
- simple: replace the single ellipsis with a deletion symbol
- better: try to find the context anyway, and show a deletion symbol at the right position

The 2nd alternative should be possible, since a deletion corresponds to an empty selection {j-j} in the menu item. This would also solve a simultaneuous insertion and deletion, e.g.:
```
{1-1,2-3} apa [] bepa [cepa] darpa
apa [cappa] bepa [] darpa
```

**Comment by fredefox** [comment]
simpler and better: Just show the resulting sentence?

**Comment by heatherleaf** [comment]
> simpler and better: Just show the resulting sentence?

But then we're back at how it was before... Here is how it looks now:

      en god kung älskar ett **~~stort~~** hus och en dator i Paris 
                               +––––––––––––––––––+
                               |               …               |
                               |   … ett **~~kallt~~** hus …   |
                               |   … ett **~~blått~~** hus …   |
                               +––––––––––––––––––+

And here is how it was before:

      en god kung älskar ett **~~stort~~** hus och en dator i Paris 
    +––––––––––––––––––––––––––––––––––––––––––––––––––+
    |      en god kung älskar ett hus och en dator i Paris       |
    |  en god kung älskar ett **kallt** hus och en dator i Paris  |
    |  en god kung älskar ett **blått** hus och en dator i Paris  |
    +––––––––––––––––––––––––––––––––––––––––––––––––––+

What I think I want is this:

      en god kung älskar ett **~~stort~~** hus och en dator i Paris 
                               +––––––––––––––––––+
                               |     … ett **∅** hus …     |
                               |   … ett **kallt** hus …   |
                               |   … ett **blått** hus …  |
                               +––––––––––––––––––+

**Comment by heatherleaf** [comment]
(I hope my ascii-art looks ok:)

**Comment by fredefox** [comment]
> (I hope my ascii-art looks ok:)

If you enclose it with ``` it will be pre-formatted.

I understand that this would be the nicest. I can implement it, but it's gonna be another exceptional way of rendering this.

**Comment by heatherleaf** [comment]
> If you enclose it with ``` it will be pre-formatted.

I know, but then I can't use **bold** or ~~strikeout~~ :)

**Comment by fredefox** [comment]
I'm a programmer. I understand *bold* and -strikeout- :D

**Comment by heatherleaf** [comment]
this was easy to implement after 87fc5efbf92eda82e332e0d421d030ef4a05dd06, so now it's hopefully working nicely
