### ISSUE TITLE
GUI: settings problem

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#76]
A bug was introduced in 781d74c. When I select e.g. Eng->Swe (but works for any lesson), click "Paris" and select "John", there a `null` error in `gen_word`, line 605:

```
jQuery.Deferred exception: settings is null gen_word@http://0.0.0.0:8080/js/app.js:605:1
show_lin@http://0.0.0.0:8080/js/app.js:642:5
show_sentences@http://0.0.0.0:8080/js/app.js:513:3
show_exercise@http://0.0.0.0:8080/js/app.js:439:3
handle_menu_response@http://0.0.0.0:8080/js/app.js:413:5
l@http://0.0.0.0:8080/js/jquery.min.js:2:29373
a/</c<@http://0.0.0.0:8080/js/jquery.min.js:2:29677
 undefined
jquery.min.js:2:30920
```

(and `show_lin` bails out, so the full sentence is not shown)

After some introspection, it seems like `settings` is null when the new sentence is about to be shown.

**Comment by fredefox** [comment]
I can't repro right now. Can you try again with bf3b92b? You may need to add --recreate when invoking muste-ajax.

**Comment by heatherleaf** [comment]
Still a problem. To reproduce:

1. select "Eng->Swe (highlight on)"
2. click "books" (or any word)
3. select "Paris" (or any menu item) from the menu

Result: 
```
jQuery.Deferred exception: settings is null gen_word@http://0.0.0.0:8080/js/app.js:605:1
show_lin@http://0.0.0.0:8080/js/app.js:642:5
show_sentences@http://0.0.0.0:8080/js/app.js:513:3
show_exercise@http://0.0.0.0:8080/js/app.js:439:3
handle_menu_response@http://0.0.0.0:8080/js/app.js:413:5
l@http://0.0.0.0:8080/js/jquery.min.js:2:29373
a/</c<@http://0.0.0.0:8080/js/jquery.min.js:2:29677
 undefined
jquery.min.js:2:30920
```

and printing of the first sentence stops after "good":
![image](https://user-images.githubusercontent.com/1324196/47363466-29a82c00-d6d7-11e8-84db-cd9ca6dba4c9.png)

**Comment by fredefox** [comment]
Super strange! Even with that step-by-step guide I can't repro...

**Comment by fredefox** [comment]
Could cache be an issue? Ctrl+Shift+r to skip cache.

**Comment by heatherleaf** [comment]
Don't know what it was -- it didn't go away by refreshing, and I got the same problem in all browsers. 

But I cleaned everything (`stack clean` and `make clean`), and started over, then it worked...
