### ISSUE TITLE
Setting: Order of exercises

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#77]
It seems like the exercises are presented in random order. 

Can there be a per-lesson setting, telling if the exercises should be in the order they are written (in `lessons.yaml`), or randomised?

Default value: non-random

**Comment by fredefox** [comment]
When a user selects a lesson for the first time an "exercise list" is generated. This is indeed a randomized subset of all the exercises.

**Comment by fredefox** [comment]
ff3c7b5 closes this.
