### ISSUE TITLE
GUI: exercise number

### ISSUE THREAD

**Issue by heatherleaf** [MUSTE-Project/MULLE#79]
The exercise is numbered from 0, but should be from 1.

I.e., when doing the first Eng->Swe exercise it says "övning 0 av 4", and when doing the final it says "övning 3 av 4"

**Comment by fredefox** [comment]
I can't reproduce this.

**Comment by heatherleaf** [comment]
here's how it looks like when I start anew (lesson: Eng->Swe):
![image](https://user-images.githubusercontent.com/1324196/47497852-b4b22f00-d85b-11e8-8448-a4008e251cb4.png)

It says "övning 0 av 4", but it should say "1 av 4"

**Comment by fredefox** [comment]
Ah! It should really read: Completed 0 of 4 exercises. That's what it's trying to tell you.

**Comment by fredefox** [comment]
Fixed in ab587fc
