### ISSUE TITLE
Create live demo instance

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#8]
Herbert has added me to his server so I am now able to push the code there.

I've looked into doing a binary deployment (i.e. build for his machine locally) but it seems a bit complicated, it would be easier if I can just have access to my build-tool (stack) on his machine. So I'm waiting to hear if he'll install that for me on his machine.

When this is up and running it should be accessible on https://cse-principia.cse.chalmers.se/mulle-dev/

>  if you have the application listening on localhost:8081 it can be accessed via https://cse-principia.cse.chalmers.se/mulle-dev/

Quoted from #5

**Comment by fredefox** [comment]
Ping @daherb

**Comment by fredefox** [comment]
Woops

**Comment by daherb** [comment]
Stack is installed now

**Comment by fredefox** [comment]
Sorry to be a bother again, I think I need at least stack > 1.6.1 to be able to leverage specifying git locations in stack.yaml. Personally I'm running 1.7.1. I installed it with

    curl -sSL https://get.haskellstack.org/ | sh

See https://docs.haskellstack.org/en/stable/README/

**Comment by daherb** [comment]
I don't like installing stuff outside the package repository. Also stack 1.7.1 requires base>=4.10 which would require a ghc upgrade. But you could for example try to install stack 1.6.5 with cabal in your own home directory

**Comment by fredefox** [comment]
Stack uses a local version of GHC that doesn't interfere with the globally installed version. I'll see if I can install it in my home-dir.

**Comment by fredefox** [comment]
... I've gotten cabal 1.7.1 now but I can't build ghc-8.4.3 it requires libncurses. I totally understand if you don't want to install all sorts of things onto your system.

@heatherleaf maybe we can put this up somewhere else?

**Comment by fredefox** [comment]
Wait. Trying to build with ghc-8.0.2

**Comment by fredefox** [comment]
I've backported digestive-functors (a dependency) and this project to work with ghc-8.0.2. Hopefully it'll build successfully now.

**Comment by fredefox** [comment]
I've managed to build it. Now I just have to make the base-path configurable. You get a 404 if you hit the URL: https://cse-principia.cse.chalmers.se/mulle-dev/

**Comment by fredefox** [comment]
FYI: I'll be looking into this now.

**Comment by fredefox** [comment]
Halleluja! We are [live](https://cse-principia.cse.chalmers.se/mulle-dev/muste.html). This is currently running 9a5a5195b0af14ccdd7eaedf6a9ea4ca20626c19.

**Comment by fredefox** [comment]
For configuration options see the [relevant section in the README](https://github.com/MUSTE-Project/MULLE/blob/9a5a5195b0af14ccdd7eaedf6a9ea4ca20626c19/README.md#configuring). For some caveats see [ditto BACKLOG](https://github.com/MUSTE-Project/MULLE/blob/9a5a5195b0af14ccdd7eaedf6a9ea4ca20626c19/BACKLOG.md#better-handling-of-build-configuration-options).
