### ISSUE TITLE
Managing gf-* as local dependencies

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#81]
I feel it's a mistake to add gf-core as a submodule. It's true you need it to build the project. Same as you need `make`. But I don't think it should be a submodule. I think it's fair enough to have gf-rgl as a dependencies because we really need to ensure that we're using the right version of the grammars - and it makes it easier to automatically build the grammars.

Any thoughts?

**Comment by fredefox** [comment]
This is of course particularly interesting because gf-core may break if it's installed in different locations *and* becuase the size of the directory after installation is 1.4 G.

**Comment by heatherleaf** [comment]
I agree that we could remove the gf-core submodule. 

Yes, gf-core could break, but shouldn't. There are more projects than ours that rely on GF

**Comment by fredefox** [comment]
Perfekt! I'll yank it out then.

**Comment by fredefox** [comment]
Closed in f76949d

**Comment by heatherleaf** [comment]
There are still some traces of `gf-core` left:

```
$ git clone https://github.com/MUSTE-Project/MULLE
$ cd MULLE/
$ git checkout fredefox
$ git submodule update --init
fatal: No url found for submodule path 'libs/gf-core' in .gitmodules

$ git grep gf-core
README.md:`gf-core`.  Please follow the guidelines in
README.md:- <https://github.com/GrammaticalFramework/gf-core>
README.md:Assuming you have set up `gf-core` and `gf-rgl`.
cabal.project:  libs/gf-core/src/runtime/haskell
muste/src/Muste/Tree/Internal.hs:-- [PR#9]: https://github.com/GrammaticalFramework/gf-core/pull/9
stack-ghc-8-6.yaml:  - git: git@github.com:MUSTE-Project/gf-core.git
stack-lts-12.yaml:- git: git@github.com:GrammaticalFramework/gf-core.git
stack-lts-9.yaml:- git: git@github.com:GrammaticalFramework/gf-core.git
```

I could remove those traces, but I don't know if I have to do something more than that

**Comment by fredefox** [comment]
> fatal: No url found for submodule path 'libs/gf-core' in .gitmodules

This is related to your local setup. You need to "deinit" the submodule.

But with the other stuff you make a good point. I'll do it.

**Comment by fredefox** [comment]
Scratch the first thing I said. Try with f82a68e

**Comment by heatherleaf** [comment]
Works fine now (tested on my MacBook with a fresh clone of the repo).

Some warnings:
```
$ stack install

Warning: Specified file "static/js/countdown.js" for data-files does not exist
Warning: Specified file "static/js/handlebars.js" for data-files does not exist
Warning: Specified file "static/js/handlebars.min.js" for data-files does not exist
Warning: Specified file "static/js/jquery.js" for data-files does not exist
Warning: Specified file "static/js/jquery.min.js" for data-files does not exist

Warning: File listed in muste-ajax/muste-ajax.cabal file does not exist: static/js/countdown.js
Warning: File listed in muste-ajax/muste-ajax.cabal file does not exist: static/js/handlebars.js
Warning: File listed in muste-ajax/muste-ajax.cabal file does not exist: static/js/handlebars.min.js
Warning: File listed in muste-ajax/muste-ajax.cabal file does not exist: static/js/jquery.js
Warning: File listed in muste-ajax/muste-ajax.cabal file does not exist: static/js/jquery.min.js
```

There are also 3 warnings of redundant imports in both `Setup.hs`:
```
/Users/peb/Documents/Repositories/MULLE-clean/muste-ajax/Setup.hs:10:1: warning: [-Wunused-imports]
    The import of ‘ExitCode, ProcFailed’
    from module ‘Turtle’ is redundant
   |
10 | import Turtle (Shell, Line, ExitCode(..), ProcFailed(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/Users/peb/Documents/Repositories/MULLE-clean/muste-ajax/Setup.hs:13:1: warning: [-Wunused-imports]
    The import of ‘liftIO’
    from module ‘Control.Monad.IO.Class’ is redundant
   |
13 | import Control.Monad.IO.Class (MonadIO(liftIO))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/Users/peb/Documents/Repositories/MULLE-clean/muste-ajax/Setup.hs:15:1: warning: [-Wunused-imports]
    The import of ‘Control.Exception’ is redundant
      except perhaps to import instances from ‘Control.Exception’
    To import instances alone, use: import Control.Exception()
   |
15 | import Control.Exception (throwIO)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

And here's another interesting warning:
```
Warning: 'license: Artistic-2.0' is not a recognised license. The known
licenses are: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD2,
BSD3, MIT, ISC, MPL-2.0, Apache, Apache-2.0, PublicDomain, AllRightsReserved,
OtherLicense
```

The GF grammars generate a lot of warnings, but that's ok. Most of them have to do with some resource grammars not complete (and therefore out of our control), some of them I can perhaps fix.

Finally, there's the problem with `Muste` and `muste` referring to the same directory because MacOS HFS+ is case-insensitive (see issue #55)

**Comment by fredefox** [comment]
*** Missing assets
Yes this is a bit annoying, the warning will only appear the very first time you build the project, however. It's probably because I'm hooking into the wrong build-step in `Setup.hs`.

*** License
The unrecognized license warning is not something to be too concerned about. I don't get it with:

```
$ stack --version && stack exec -- cabal --version
Version 1.10.0, Git revision 7015fda333bbfb803d7e04e8dec5c8046f088976 (6495 commits) x86_64 hpack-0.30.0
cabal-install version 2.2.0.0
compiled using version 2.2.0.1 of the Cabal library
```

So I expect they've added that license in a later version. We should add the `license-file` field though and perhaps move the license to the root of the repo and symlink them from `muste{,-ajax}`.

**Comment by fredefox** [comment]
I did the thing with the licenses in 8c9af77. I don't know if it will silence the warning for you with your version of cabal.

**Comment by fredefox** [comment]
So the warning doesn't come up if I build with cabal, so I will say this is an issue that should be fixed upstream in stack.

**Comment by fredefox** [comment]
> because the size of the directory after installation is 1.4 G.

This is not entirely accurate:

```
$ du -sh libs/gf-core .git/modules/libs/gf-core dist-newstyle .stack-work
24M	libs/gf-core
131M	.git/modules/libs/gf-core
430M	dist-newstyle
1.6G	.stack-work
```

The first two directories are only needed if we build with cabal (but will however be included regardless). The build-artifacts in the last two directories depend on whether you build with cabal or stack.

One of the reasons stack is taking up so much more space in this case is because I have build with a lot of different package combinations and I just ran cabal a-fresh to test this.

So I'll close this now.
