### ISSUE TITLE
White space characters

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#83]
I tried to find out what the standards are for displaying invisible characters but couldn't find a good reference. Here's what my editors (emacs) happens to do:

```
Spaces:      · MIDDLE DOT
Tabulations: » RIGHT-POINTING DOUBLE ANGLE
Newlines:    $ DOLLAR SIGN
```

**Comment by fredefox** [comment]
And to be precise, my proposal is to stick to this - or if someone has a better reference than some random dusty editor from the 70'ies xD

**Comment by heatherleaf** [comment]
this is now handled in the CSS, so it should be quite straightforward to change to whatever someone likes:

https://github.com/MUSTE-Project/MULLE/blob/87fc5efbf92eda82e332e0d421d030ef4a05dd06/muste-ajax/static/css/muste.css#L315-L336
