### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by daherb** [MUSTE-Project/MULLE#89]
Make it easier to translate the user interface

**Comment by daherb** [comment]
Aarne suggests use GF for the translation (use functions/abstract syntax trees instead of strings)

**Comment by heatherleaf** [comment]
It seems a bit complex to use GF for that, so I instead decided on a JS i18n framework ([i18next](https://www.i18next.com/)). Use the attribute `data-i18n` in the html code, like this:

https://github.com/MUSTE-Project/MULLE/blob/87fc5efbf92eda82e332e0d421d030ef4a05dd06/muste-ajax/static/index.html#L86-L96

and add the translations to your i18n config file, in the `i18n` [directory](https://github.com/MUSTE-Project/MULLE/tree/develop/muste-ajax/static/i18n)
