### ISSUE TITLE
Represent ambiguities

### ISSUE THREAD

**Issue by fredefox** [MUSTE-Project/MULLE#9]
So, with the implementation of issue #3 we do have a representation
that allows for multiple `TTree`s to be associated with a given
`ServerTree` and ditto `ClientTree`, however, ambiguities are not
actually every introduced.  This is the main challenge; introducing
ambiguities.  I have an idea on how to address this.  It consists of
introducing a new type `Ambiguous` (alternatively perhaps modifying
`Linearization`).  The advantage of doing it this way is threefold:
testability, separation of concerns and it will make the code easier
to understand.

### Current implementation

I have analyzed the current implementation: As it stands right now the
it is not very easy to see how ambiguities are supposed to be
introduced.  Here is how the application works ATM when a user opens a
lesson:

1. A lesson contains two `TTree`s.  These are fetched from the
   database (c.f. `Protocol.handleLessonInit`,
   `Database.startLesson`).  There can be no ambiguity at this point.
2. For both source and target tree we create a menu
   (c.f. `Muste.getCleanMenu`)
3. A menu contains mappings from paths to `CostTree`s, but a
   `CostTree` are still unambiguous!  A `CostTree` is basically the
   same as a `TTree` with some extra information: The "cost", is it an
   "insertion", ...
4. When a user picks one of these `CostTree`s from the menu a request
   is send back to the server.  This request contains a `TTree`, but
   that `TTree` should really only be considered seen as it's
   linearization - since the user has no way of knowing the underlying
   grammatical representation.  This is where I think it would make
   sense to have a new type `Ambiguous` representing a sentence that
   can be understood as multiple `TTree`s.  If it should be a new type
   or if we should just modify `Linearization` somehow I don't know.

### Proposed fix:

Here is some technical details about how to achieve the separation of
concerns.

1. Move knowledge of .pfg files to the `muste` package.
2. Embed files into the `mute` runtime with e.g. the package
   `file-embed`.
3. Create map from grammar identifier to this binary blob.
4. Add this identifier as a projection to a new type `Ambiguous` which
   has a collection of `TTree`s.
5. Now we can parse an `Ambiguous` in a pure fashion - that is make
   `readPGF` pure and then we can use that and a variant of
   `parseTTree` to make a valid `Show` (alternatively `Pretty`)
   instance for `Ambiguous` that uses the concrete syntax of `pgf`.
   The `Show` values most include as a minimum a reference to this
   identifier.
6. Make corresponding `Read` instance.

Now we can fix the original issue.  A `Menu` should not map to
`TTree`s but rather to a set of `Ambiguous`.

### Test strategy

After all this it will be way easier to test other functions since we
don't have to labor with transforming a specification (as in the case
of [this comment]).  So now we write a test for
`Protocol.assembleMenus`.  To make it testable we must first make an
internal version of that module:

1. Make internal module
2. Rexport stuff in old location

Make test suite for `muste-ajax` including the following test:

The sentence "fienden besegrar Afrika":

    useS (useCl (simpleCl (useCNdefsg   (useN hostis_N)) (transV vincere_V2 (usePN Africa_PN))))

gets translated to the Latin "hostis Africam vincit" which represents
the following

    useS (useCl (simpleCl (useCNdefsg   (useN hostis_N)) (transV vincere_V2 (usePN Africa_PN))))
    useS (useCl (simpleCl (useCNindefsg (useN hostis_N)) (transV vincere_V2 (usePN Africa_PN))))

[this comment]: https://github.com/MUSTE-Project/MULLE/issues/3#issuecomment-409828645

**Comment by heatherleaf** [comment]
I'm not sure I understand the need for this issue. You have already moved from single to multiple trees, so you should already be able to handle ambiguous grammars. For what do you need the type `Ambiguous`?

The invariant in a `ServerTree` (and `ClientTree`) should be that all its trees have the same linearisation, and that they are all trees with that linearisation. 

This will also change the formal definition of what is an "exercise": it's not a pair of `TTree`s, but a pair of `TTree` sets. Because of the invariant, it might be easier to store exercises as a pair of linearisations, and create the initial tree sets by parsing the linearisations.

(Note: you use "lesson", but according to @daherb 's terminology, a "lesson" is a grammar pair (e.g., `PrimaLat`, `PrimaSwe`), and an "exercise" is the actual pair of sentences/trees).

**Comment by fredefox** [comment]
Perhaps you're right. As you pointed out it should be possible to just change `CostTree`
