### ISSUE TITLE
Use Github Project instead of Github Issues

### ISSUE THREAD

**Issue by daherb** [MUSTE-Project/MULLE#92]
No text

**Comment by heatherleaf** [comment]
probably a good idea... anyone volunteering in setting this up? ;)

**Comment by fredefox** [comment]
What's GitHub project? GitHub pages?

**Comment by daherb** [comment]
It's this: https://help.github.com/en/articles/about-project-boards, the tab is right next to pull requests

**Comment by daherb** [comment]
Actually it seems that you can combine both

**Comment by heatherleaf** [comment]
Ok, all issues are now added here: 
https://github.com/MUSTE-Project/MULLE/projects/1
